version: '3'
services:
  connector-zerofox:
    image: opencti/connector-zerofox:latest
    environment:
      - OPENCTI_URL=ChangeMe
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      # - CONNECTOR_NAME=ZeroFox
      # - CONNECTOR_SCOPE=zerofox
      # - CONNECTOR_LOG_LEVEL=error
      # - CONNECTOR_DURATION_PERIOD=P1D # optional, ISO 8601 duration, default 1 day
      # - CONNECTOR_UPDATE_EXISTING_DATA=false # optional, default false
      - ZEROFOX_USERNAME=ChangeMe # required
      - ZEROFOX_PASSWORD=ChangeMe # required
      # - ZEROFOX_COLLECTORS= # optional, comma-separated feeds, default all feeds
      # - ZEROFOX_FIRST_RUN=P1D # optional, ISO 8601 duration or absolute date, default P1D
    restart: always
