version: '3'
services:
  connector-proofpoint-tap:
    # image: opencti/connector-proofpoint-tap:latest
    build: .
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2cb9340e-e4cd-46c1-ad42-62cf70e243a8
      - CONNECTOR_ID=ext-imp--proofpoint-tap--uuid
      - "CONNECTOR_NAME=Proofpoint TAP"
      - CONNECTOR_SCOPE=report
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_DURATION_PERIOD=PT1H
      - TAP_API_BASE_URL=https://tap-api-v2.proofpoint.com/
      - TAP_API_PRINCIPAL=ChangeMe
      - TAP_API_SECRET=ChangeMe
#      - TAP_API_TIMEOUT=PT30S
#      - TAP_API_RETRIES=3
#      - TAP_API_BACKOFF=PT5S
      - TAP_MARKING_DEFINITION=white
      - TAP_EXPORT_CAMPAIGNS=False
      - TAP_EXPORT_EVENTS=True
      - TAP_EVENTS_TYPE=all
    restart: always
    networks:
      - filigran_default
networks:
  filigran_default:
    external: true
