FROM redhat/ubi9-minimal

ENV PYTHONDONTWRITEBYTECODE=1

# Set environment variable
ENV CONNECTOR_TYPE=EXTERNAL_IMPORT

# Set working directory
WORKDIR /opt/connector/src

# Copy requirements and install Python dependencies
COPY requirements.txt /tmp/requirements.txt

# Copy the connector
COPY src /opt/connector/src
COPY docs /opt/connector/docs

RUN set -eux; \
    microdnf -y --setopt=install_weak_deps=0 install -y python3.12 python3.12-pip git libxslt libxml2; \
    microdnf clean all

# Install Python dependencies
RUN pip3.12 install --no-cache-dir -r /tmp/requirements.txt

# Install TI API lib
RUN pip3.12 install /opt/connector/src/lib/cyberintegrations-0.13.1-py3-none-any.whl

# Clean up unnecessary files
RUN microdnf clean all && \
    rm -rf /var/cache/yum && \
    rm -rf /root/.cache

CMD ["python3.12", "main.py"]

