version: '3'
services:
  connector-censys-enrichmentapis:
    image: opencti/connector-censys-enrichmentapis:latest # 'censys-enrichmentapis' being the name of connector's directory
    environment:
      # Generic parameters (connection with OpenCTI)
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      # Common parameters for connectors of type INTERNAL_ENRICHMENT
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_NAME=CHANGEME # optional (default: 'Template Connector')
      - CONNECTOR_SCOPE=CHANGEME
      - CONNECTOR_LOG_LEVEL=error # optional (default: 'error')
      - CONNECTOR_AUTO=false # optional (default: false)
      # Custom parameters for connector-censys-enrichmentapis
      - CENSYS_ENRICHMENTAPIS_API_BASE_URL=CHANGEME
      - CENSYS_ENRICHMENTAPIS_API_KEY=CHANGEME
      - CENSYS_ENRICHMENTAPIS_MAX_TLP_LEVEL=amber+strict # optional, available values: 'clear', 'white', 'green', 'amber', 'amber+strict', 'red' (default: 'amber+strict')
    restart: always
