version: '3'
services:
  connector-swimlane:
    image: opencti/connector-swimlane:rolling
    environment:
      # Generic parameters (connection with OpenCTI)
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      # Common parameters for connectors of type EXTERNAL_IMPORT
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_NAME=Swimlane # optional (default: 'Swimlane')
      - CONNECTOR_SCOPE=swimlane # optional
      - CONNECTOR_LOG_LEVEL=error # optional (default: 'error')
      - CONNECTOR_DURATION_PERIOD=PT15M # optional (default: 'PT15M')
      # Swimlane parameters
      - SWIMLANE_API_BASE_URL=CHANGEME # e.g. https://swimlane.example.com
      - SWIMLANE_API_TOKEN=CHANGEME
      - SWIMLANE_APPLICATION_ID=CHANGEME
      - SWIMLANE_MAX_RECORDS=100 # optional (default: 100)
      - SWIMLANE_TLP_LEVEL=amber # optional (default: 'amber')
      - SWIMLANE_SSL_VERIFY=true # optional (default: true)
    restart: always
