version: "3"
services:
  connector-vulncheck:
    image: opencti/connector-vulncheck:6.6.14
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_VULNCHECK_API_KEY=CHANGEME
    restart: always
