opencti:
  url: "http://localhost:8080"
  token: "ChangeMe"

connector:
  id: "ChangeMe" # Must be a valid UUIDv4 (e.g. generated via `uuidgen`)
  type: "INTERNAL_ENRICHMENT"
  name: "WhoisFreaks"
  scope: "Domain-Name,IPv4-Addr,IPv6-Addr"
  auto: false # Manual trigger recommended to manage API quota
  confidence_level: 100
  log_level: "INFO"

whoisfreaks:
  api_key: "ChangeMe"
