version: '3'
services:
  connector-proofpoint-et-intelligence:
    image: opencti/connector-proofpoint-et-intelligence:latest
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # Connector's definition parameters REQUIRED
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=ProofPoint ET Intelligence
      - CONNECTOR_SCOPE=IPv4-Addr,Domain-Name,StixFile
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_AUTO=true

      # Connector's custom execution parameters
      - PROOFPOINT_ET_INTELLIGENCE_API_BASE_URL=https://api.emergingthreats.net/v1/
      - PROOFPOINT_ET_INTELLIGENCE_API_KEY=ChangeMe
      - PROOFPOINT_ET_INTELLIGENCE_MAX_TLP=TLP:AMBER+STRICT
      - PROOFPOINT_ET_INTELLIGENCE_IMPORT_LAST_SEEN_TIME_WINDOW=P30D
    restart: always
