# -*- coding: utf-8 -*-
"""Convert an XposedOrNot lookup result into STIX objects.

The enrichment is deliberately conservative to keep graphs clean:
  - the source Email-Addr observable is updated in place (score, labels,
    external reference) by the connector;
  - the per-breach detail lands in one markdown Note attached to the
    observable, rendered by OpenCTI.
"""

from __future__ import annotations

from typing import Any

from connectors_sdk.models import Note, OrganizationAuthor, Reference, TLPMarking


def _md_cell(value: Any) -> str:
    """Make a value safe for a one-line markdown table cell."""
    text = str(value if value is not None else "—")
    return text.replace("|", "\\|").replace("\n", " ").strip() or "—"


def _fmt_records(value) -> str:
    try:
        return "{:,}".format(int(value))
    except (TypeError, ValueError):
        return "—"


class ConverterToStix:
    """Build the Note describing the breach exposure of an email address."""

    def __init__(self, author: OrganizationAuthor, tlp: TLPMarking):
        self.author = author
        self.tlp = tlp

    @staticmethod
    def make_author() -> OrganizationAuthor:
        return OrganizationAuthor(
            name="XposedOrNot",
            description=(
                "Breach exposure data provided by the XposedOrNot API"
                " (https://xposedornot.com)."
            ),
            organization_type="vendor",
        )

    @staticmethod
    def years(breaches: list[dict]) -> tuple[int | None, int | None]:
        years = []
        for breach in breaches:
            try:
                years.append(int(str(breach.get("date"))[:4]))
            except (TypeError, ValueError):
                continue
        return (min(years), max(years)) if years else (None, None)

    @staticmethod
    def has_plaintext_exposure(breaches: list[dict]) -> bool:
        return any(b.get("password_risk") == "plaintextpassword" for b in breaches)

    def build_note(self, source_id: str, result: dict) -> Note:
        breaches = result.get("breaches") or []
        first_year, latest_year = self.years(breaches)
        total_records = sum(b.get("records") or 0 for b in breaches)

        lines = [
            "## XposedOrNot — breach exposure summary",
            "",
            "**Breaches found:** %d  " % len(breaches),
        ]
        if first_year and latest_year:
            lines.append(
                "**First exposure:** %s — **Latest:** %s  " % (first_year, latest_year)
            )
        if total_records:
            lines.append(
                "**Total records across breaches:** {:,}  ".format(total_records)
            )
        if result.get("risk_label"):
            score = result.get("risk_score")
            lines.append(
                "**Overall risk:** %s%s  "
                % (
                    result["risk_label"],
                    " (%s/100)" % score if score is not None else "",
                )
            )
        if self.has_plaintext_exposure(breaches):
            lines.append("")
            lines.append("⚠️ **At least one breach stored passwords in plaintext.**")
        lines += [
            "",
            "| Breach | Date | Records | Domain | Exposed data | Password risk | Verified |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for breach in breaches:
            lines.append(
                "| %s | %s | %s | %s | %s | %s | %s |"
                % (
                    _md_cell(breach.get("name")),
                    _md_cell(breach.get("date")),
                    _fmt_records(breach.get("records")),
                    _md_cell(breach.get("domain")),
                    _md_cell(", ".join(breach.get("data_classes") or [])),
                    _md_cell(breach.get("password_risk")),
                    _md_cell(breach.get("verified")),
                )
            )
        lines += [
            "",
            "_Generated by the XposedOrNot connector"
            " ([xposedornot.com](https://xposedornot.com))._",
            # Hidden marker: keeps the Note's generated STIX id unique per source
            # observable (the SDK derives the id from content/abstract only, not
            # object_refs) while staying stable across re-enrichments. Does not
            # render in OpenCTI's markdown view.
            "<!-- xon-source:%s -->" % source_id,
        ]

        return Note(
            abstract="XposedOrNot — exposed in %d data breach(es)" % len(breaches),
            content="\n".join(lines),
            objects=[Reference(id=source_id)],
            note_types=["analysis"],
            labels=["xposedornot", "data-breach"],
            author=self.author,
            markings=[self.tlp],
        )
