version: '3'
services:
  connector-socradar:
    image: opencti/connector-socradar:latest
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe

      # Connector's definition parameters REQUIRED
      - CONNECTOR_ID=ChangeMe
      # - CONNECTOR_NAME=SOCRadar # Default SOCRadar
      # - CONNECTOR_SCOPE=socradar # Default socradar
      # - CONNECTOR_LOG_LEVEL=error # Default error
      # - CONNECTOR_DURATION_PERIOD=PT10M # ISO8601 format in String, start with 'P...' for Period. Default PT10M

      # Connector's custom execution parameters
      - RADAR_BASE_FEED_URL=https://platform.socradar.com/api/threat/intelligence/feed_list/ # required
      - RADAR_SOCRADAR_KEY=ChangeMe
      - 'RADAR_FEED_LISTS={"feed_list_1":"ID_1","feed_list_2":"ID_2"}'
    restart: always
