FROM registry.access.redhat.com/ubi9/ubi-minimal

ARG PYTHON_VERSION="3.12"
ARG EXTRA_PACKAGES=""

RUN set -eux; \
    microdnf -y --setopt=install_weak_deps=0 install python${PYTHON_VERSION} ${EXTRA_PACKAGES}; \
    microdnf clean all;

ENV PYTHONDONTWRITEBYTECODE=1

ARG CONNECTOR_TYPE
ENV CONNECTOR_TYPE=${CONNECTOR_TYPE}

ARG CONNECTOR_CMD="main.py"
ARG CONNECTOR_WORKDIR="/opt/connector/src"
ARG POST_INSTALL=""

ENV CONNECTOR_CMD=${CONNECTOR_CMD}

COPY src /opt/connector/src

RUN set -eux; \
    microdnf -y --setopt=install_weak_deps=0 install python${PYTHON_VERSION}-pip git-core; \
    pip${PYTHON_VERSION} install --no-cache-dir -r /opt/connector/src/requirements.txt; \
    if [ -n "${POST_INSTALL}" ]; then ${POST_INSTALL}; fi; \
    microdnf -y remove python${PYTHON_VERSION}-pip git-core ; \
    microdnf clean all;

WORKDIR ${CONNECTOR_WORKDIR}

CMD python${PYTHON_VERSION} ${CONNECTOR_CMD}
