"""Offer models."""

from connectors_sdk.models.octi import (
    URL,
    AssociatedFile,
    AttackPattern,
    BaseEntity,
    BaseIdentifiedEntity,
    City,
    Country,
    DomainName,
    ExternalReference,
    File,
    Indicator,
    Individual,
    IntrusionSet,
    IPV4Address,
    IPV6Address,
    KillChainPhase,
    Malware,
    Note,
    Organization,
    OrganizationAuthor,
    Relationship,
    Report,
    Sector,
    Software,
    ThreatActorGroup,
    TLPMarking,
    Vulnerability,
)

__all__ = [
    # Typing purpose
    "BaseEntity",
    "BaseIdentifiedEntity",
    # Models flat list
    "AssociatedFile",
    "AttackPattern",
    "City",
    "Country",
    "DomainName",
    "ExternalReference",
    "File",
    "Indicator",
    "Individual",
    "IntrusionSet",
    "IPV4Address",
    "IPV6Address",
    "KillChainPhase",
    "Malware",
    "Note",
    "Organization",
    "OrganizationAuthor",
    "Relationship",
    "Report",
    "Sector",
    "Software",
    "ThreatActorGroup",
    "TLPMarking",
    "URL",
    "Vulnerability",
]
