"""MediaContent."""

from connectors_sdk.models.base_observable_entity import BaseObservableEntity
from pycti import CustomObservableMediaContent
from pydantic import AwareDatetime, Field


class MediaContent(BaseObservableEntity):
    """Represent a Media Content observable."""

    url: str = Field(
        description="The URL of the media content.",
        min_length=1,
    )
    title: str | None = Field(
        default=None,
        description="The title of the media content.",
    )
    content: str | None = Field(
        default=None,
        description="The content body of the media content.",
    )
    media_category: str | None = Field(
        default=None,
        description="Category of the media content.",
    )
    publication_date: AwareDatetime | None = Field(
        default=None,
        description="Publication date of the media content.",
    )

    def to_stix2_object(self) -> CustomObservableMediaContent:
        """Make custom STIX object.
        STIX ID is generated by pycti based on the 'url' attribute.
        """
        return CustomObservableMediaContent(
            url=self.url,
            title=self.title,
            content=self.content,
            media_category=self.media_category,
            publication_date=self.publication_date,
            **self._common_stix2_properties(),
        )
