version: '3'
services:
  connector-malanta-attribution:
    image: opencti/connector-malanta-attribution:6.9.0
    environment:
      # Generic parameters (connection with OpenCTI)
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      # Common parameters for connectors of type STREAM
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_NAME=Malanta Attribution # optional (default: 'Malanta Attribution')
      - CONNECTOR_SCOPE=indicator # optional (default: 'indicator')
      - CONNECTOR_LOG_LEVEL=error # optional (default: 'error')
      - CONNECTOR_LIVE_STREAM_ID=CHANGEME # ID of the live stream created in the OpenCTI UI
      - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=false # optional (default: false)
      - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true # optional (default: true)
      # Custom parameters for connector-malanta-attribution
      - MALANTA_ATTRIBUTION_LABEL_PREFIX=apt: # optional (default: 'apt:')
      - MALANTA_ATTRIBUTION_ACTOR_SEPARATORS=, # optional (default: ',')
      - MALANTA_ATTRIBUTION_AUTHOR_NAME=Malanta.ai # optional (default: 'Malanta.ai')
      - MALANTA_ATTRIBUTION_CREATE_INTRUSION_SETS=true # optional (default: true)
      - MALANTA_ATTRIBUTION_MIN_CONFIDENCE=0 # optional (default: 0)
    restart: always
