version: '3'
services:
  connector-scoring-calculator:
    image: opencti/connector-scoring-calculator:latest
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # Connector's definition parameters REQUIRED
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=Scoring calculator
      - CONNECTOR_SCOPE=Indicator
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_AUTO=true

      # Connector's custom execution parameters
      - CONNECTOR_SCORING_HIGH_PRIORITY_LABELS=["[Scoring] High priority"]
      - CONNECTOR_SCORING_MEDIUM_PRIORITY_LABELS=["[Scoring] Medium priority"]
      - CONNECTOR_SCORING_LOW_PRIORITY_LABELS=["[Scoring] Low priority"]
      - CONNECTOR_SCORING_INDICATOR_TYPE_ENRICHABLE=IPv4-Addr,IPv6-Addr,Domain-Name,StixFile
      - CONNECTOR_SCORING_BROWSE_REPORT=false

      - CONNECTOR_SCORING_THREAT_IMPACT_SCORE=true
      - CONNECTOR_SCORING_THREAT_HIGH_PRIORITY=20
      - CONNECTOR_SCORING_THREAT_MEDIUM_PRIORITY=10
      - CONNECTOR_SCORING_THREAT_LOW_PRIORITY=5

      - CONNECTOR_SCORING_TOOLBOX_IMPACT_SCORE=true
      - CONNECTOR_SCORING_TOOLBOX_HIGH_PRIORITY=20
      - CONNECTOR_SCORING_TOOLBOX_MEDIUM_PRIORITY=10
      - CONNECTOR_SCORING_TOOLBOX_LOW_PRIORITY=5

      - CONNECTOR_SCORING_LOCATION_IMPACT_SCORE=false
      - CONNECTOR_SCORING_LOCATION_HIGH_PRIORITY=20
      - CONNECTOR_SCORING_LOCATION_MEDIUM_PRIORITY=10
      - CONNECTOR_SCORING_LOCATION_LOW_PRIORITY=5

      - CONNECTOR_SCORING_SECTOR_IMPACT_SCORE=false
      - CONNECTOR_SCORING_SECTOR_HIGH_PRIORITY=20
      - CONNECTOR_SCORING_SECTOR_MEDIUM_PRIORITY=10
      - CONNECTOR_SCORING_SECTOR_LOW_PRIORITY=5

      - CONNECTOR_SCORING_TTP_IMPACT_SCORE=false
      - CONNECTOR_SCORING_TTP_HIGH_PRIORITY=20
      - CONNECTOR_SCORING_TTP_MEDIUM_PRIORITY=10
      - CONNECTOR_SCORING_TTP_LOW_PRIORITY=5

      - CONNECTOR_SCORING_AUTHOR_IMPACT_SCORE=false
      - CONNECTOR_SCORING_AUTHOR_HIGH_PRIORITY=20
      - CONNECTOR_SCORING_AUTHOR_MEDIUM_PRIORITY=10
      - CONNECTOR_SCORING_AUTHOR_LOW_PRIORITY=5

    restart: always

