version: '3'
services:
  connector-taxii-post:
    image: opencti/connector-taxii-post:latest
    environment:
      # Generic parameters (connection with OpenCTI)
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # Common parameters for connectors of type STREAM
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_LIVE_STREAM_ID=ChangeMe # ID of the live stream created in the OpenCTI UI
      # - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true # optional (default: true)
      # - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true # optional (default: true)
      # - "CONNECTOR_NAME=TAXII POST" # optional (default: 'TAXII POST')
      # - CONNECTOR_SCOPE=taxii # optional (default: 'taxii')
      # - CONNECTOR_LOG_LEVEL=error # optional (default: 'error')
      # TAXII POST parameters
      - TAXII_URL=https://taxii.changeme.com # The URL of the TAXII Server
      - TAXII_COLLECTION_ID=ChangeMe # The collection ID
      # - TAXII_SSL_VERIFY=true # optional (default: true)
      # - TAXII_API_ROOT=root # optional (default: 'root'), path segment between server URL and /collections/
      # - TAXII_TOKEN= # optional, token for bearer auth (if set, will ignore basic auth params)
      # - TAXII_LOGIN= # optional, login for basic auth
      # - TAXII_PASSWORD= # optional, password for basic auth
      # - TAXII_VERSION=2.1 # optional (default: '2.1'), version for TAXII
      # - TAXII_STIX_VERSION=2.1 # optional (default: '2.1'), version for STIX
      # - TAXII_DELETE_CREATED_BY_REF=true # optional (default: true)
      # - TAXII_DELETE_MARKING_DEFINITION=true # optional (default: true)
    restart: always
