services:
  connector-stream-exporter-local:
    build:
      context: ../../stream/stream-exporter
    image: local/connector-stream-exporter:dev
    container_name: connector-stream-exporter-local
    restart: unless-stopped
    environment:
      - OPENCTI_URL=${OPENCTI_URL_DOCKER}
      - OPENCTI_TOKEN=${OPENCTI_TOKEN}
      - CONNECTOR_ID=${EXPORTER_CONNECTOR_ID}
      - CONNECTOR_NAME=${EXPORTER_CONNECTOR_NAME}
      - CONNECTOR_SCOPE=stream-exporter
      - CONNECTOR_CONFIDENCE_LEVEL=80
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_LIVE_STREAM_ID=${CONNECTOR_LIVE_STREAM_ID}
      - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true
      - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=false
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_FOLDER=${MINIO_FOLDER}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_CERT_CHECK=${MINIO_CERT_CHECK}
      - WRITE_EVERY_SEC=${EXPORTER_WRITE_EVERY_SEC}

  connector-stream-importer-local:
    build:
      context: ../../external-import/stream-importer
    image: local/connector-stream-importer:dev
    container_name: connector-stream-importer-local
    restart: unless-stopped
    environment:
      - OPENCTI_URL=${OPENCTI_URL_DOCKER}
      - OPENCTI_TOKEN=${OPENCTI_TOKEN}
      - CONNECTOR_ID=${IMPORTER_CONNECTOR_ID}
      - CONNECTOR_NAME=${IMPORTER_CONNECTOR_NAME}
      - CONNECTOR_SCOPE=stream-importer
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_RUN_EVERY=${IMPORTER_RUN_EVERY}
      - CONNECTOR_UPDATE_EXISTING_DATA=${IMPORTER_UPDATE_EXISTING_DATA}
      - PERFECT_SYNC=${IMPORTER_PERFECT_SYNC}
      - MQ_HOST_OVERRIDE=host.docker.internal
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_SRC_PATH=${MINIO_SRC_PATH}
      - MINIO_DST_PATH=${MINIO_DST_PATH}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_CERT_CHECK=${MINIO_CERT_CHECK}
