services:
  connector-threat-actor-enrichment:
    build: .
    container_name: opencti-connector-threat-actor-enrichment
    restart: unless-stopped
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_THREAT_ACTOR_ENRICHMENT_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Threat Actor Enrichment
      - CONNECTOR_SCOPE=threat-actor-group
      - CONNECTOR_LOG_LEVEL=info
      - THREAT_ACTOR_ENRICHMENT_INTERVAL=24
