version: '3'
services:
  connector-fortiedr:
    image: opencti/connector-fortiedr:latest
    environment:
      # Generic parameters (connection with OpenCTI)
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # Common parameters for connectors of type STREAM
      - CONNECTOR_ID=ChangeMe
      # - CONNECTOR_NAME=FortiEDR # optional (default: 'FortiEDR')
      # - CONNECTOR_SCOPE=fortiedr # optional (default: 'fortiedr')
      # - CONNECTOR_LOG_LEVEL=error # optional (default: 'error')
      - CONNECTOR_LIVE_STREAM_ID=ChangeMe # ID of the live stream created in the OpenCTI UI
      # - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true # optional (default: true)
      # - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true # optional (default: true)
      # FortiEDR parameters
      - FORTIEDR_API_BASE_URL=ChangeMe # e.g. https://console.fortiedr.example.com
      # - FORTIEDR_ORGANIZATION= # optional, required on multi-tenant consoles
      - FORTIEDR_USERNAME=ChangeMe
      - FORTIEDR_PASSWORD=ChangeMe
      # - FORTIEDR_IP_SET_NAME=OpenCTI # optional (default: 'OpenCTI')
      # - FORTIEDR_SSL_VERIFY=true # optional (default: true)
    restart: always
