"""
Mock IPGeolocation.io API responses for unit tests.
Matches the actual v3 API response schemas.
"""

MOCK_IPGEO_FULL = {
    "ip": "2.56.188.34",
    "hostname": "malicious-host.example.com",
    "domain": "example.com",
    "location": {
        "continent_code": "NA",
        "continent_name": "North America",
        "country_code2": "US",
        "country_code3": "USA",
        "country_name": "United States",
        "country_name_official": "United States of America",
        "country_capital": "Washington, D.C.",
        "state_prov": "Texas",
        "state_code": "US-TX",
        "district": "Dallas",
        "city": "Dallas",
        "locality": "Dallas",
        "accuracy_radius": "20",
        "confidence": "High",
        "zipcode": "75201",
        "latitude": "32.7767",
        "longitude": "-96.7970",
        "is_eu": False,
        "country_flag": "https://ipgeolocation.io/static/flags/us_64.png",
        "geoname_id": "4684888",
        "country_emoji": "\U0001f1fa\U0001f1f8",
    },
    "asn": {
        "as_number": "AS15169",
        "organization": "Google LLC",
        "country": "US",
        "type": "hosting",
        "domain": "google.com",
        "date_allocated": "2000-03-30",
        "rir": "ARIN",
    },
    "company": {
        "name": "Google LLC",
        "type": "hosting",
        "domain": "google.com",
    },
    "network": {
        "connection_type": "hosting",
        "route": "2.56.188.0/24",
        "is_anycast": False,
    },
    "time_zone": {
        "name": "America/Chicago",
        "offset": -6,
        "offset_with_dst": -5,
        "current_time": "2026-01-15 10:30:00.000-0600",
        "is_dst": False,
        "dst_savings": 1,
        "dst_exists": True,
        "dst_start": "2026-03-08T02:00:00",
        "dst_end": "2026-11-01T02:00:00",
    },
    "currency": {
        "code": "USD",
        "name": "US Dollar",
        "symbol": "$",
    },
    "security": {
        "threat_score": 80,
        "is_tor": False,
        "is_proxy": True,
        "proxy_provider_names": ["Zyte Proxy"],
        "proxy_confidence_score": 80,
        "proxy_last_seen": "2025-12-12",
        "is_residential_proxy": True,
        "is_vpn": True,
        "vpn_provider_names": ["Nord VPN"],
        "vpn_confidence_score": 80,
        "vpn_last_seen": "2026-01-19",
        "is_relay": False,
        "relay_provider_name": "",
        "is_anonymous": True,
        "is_known_attacker": True,
        "is_bot": False,
        "is_spam": False,
        "is_cloud_provider": True,
        "cloud_provider_name": "Packethub S.A.",
    },
    "abuse": {
        "route": "2.56.188.0/24",
        "country": "PA",
        "name": "Packethub Abuse",
        "organization": "Packethub S.A.",
        "kind": "group",
        "address": "Office 76, Plaza 2000, Panama City, Panama",
        "emails": ["abuse@packethub.net"],
        "phone_numbers": ["+507-123-4567"],
    },
}


MOCK_IPGEO_CLEAN = {
    "ip": "8.8.8.8",
    "hostname": "",
    "domain": "",
    "location": {
        "continent_code": "NA",
        "continent_name": "North America",
        "country_code2": "US",
        "country_code3": "USA",
        "country_name": "United States",
        "country_name_official": "United States of America",
        "country_capital": "Washington, D.C.",
        "state_prov": "California",
        "state_code": "US-CA",
        "district": "Santa Clara",
        "city": "Mountain View",
        "locality": "Mountain View",
        "zipcode": "94043",
        "latitude": "37.42240",
        "longitude": "-122.08421",
        "is_eu": False,
        "geoname_id": "6301403",
        "country_emoji": "\U0001f1fa\U0001f1f8",
    },
    "asn": {
        "as_number": "AS15169",
        "organization": "Google LLC",
        "country": "US",
        "type": "hosting",
        "domain": "google.com",
        "date_allocated": "",
        "rir": "ARIN",
    },
    "company": {
        "name": "Google LLC",
        "type": "hosting",
        "domain": "google.com",
    },
    "network": {
        "connection_type": "hosting",
        "route": "8.8.8.0/24",
        "is_anycast": True,
    },
    "time_zone": {
        "name": "America/Los_Angeles",
        "offset": -8,
        "current_time": "2026-01-15 08:30:00.000-0800",
    },
    "currency": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "security": {
        "threat_score": 0,
        "is_tor": False,
        "is_proxy": False,
        "is_residential_proxy": False,
        "is_vpn": False,
        "is_relay": False,
        "is_anonymous": False,
        "is_known_attacker": False,
        "is_bot": False,
        "is_spam": False,
        "is_cloud_provider": True,
        "cloud_provider_name": "Google LLC",
    },
    "abuse": {
        "route": "8.8.8.0/24",
        "country": "",
        "name": "Abuse",
        "organization": "Abuse",
        "kind": "group",
        "address": "1600 Amphitheatre Parkway, Mountain View, CA 94043",
        "emails": ["network-abuse@google.com"],
        "phone_numbers": ["+1-650-253-0000"],
    },
}


MOCK_ASN_DETAILED = {
    "asn": {
        "as_number": "AS17557",
        "organization": "Pakistan Telecommunication Company Limited",
        "country": "PK",
        "type": "ISP",
        "domain": "ptcl.net",
        "date_allocated": "",
        "asn_name": "PKTELECOM-AS-PK",
        "allocation_status": "",
        "num_of_ipv4_routes": "1305",
        "num_of_ipv6_routes": "7",
        "rir": "APNIC",
        "routes": ["39.32.0.0/14", "39.36.0.0/16", "58.27.128.0/17"],
        "downstreams": [
            {"as_number": "AS9387", "description": "AUGERE-PK", "country": "PK"},
            {
                "as_number": "AS9541",
                "description": "Cyber Internet Services",
                "country": "PK",
            },
        ],
        "upstreams": [
            {
                "as_number": "AS6453",
                "description": "TATA COMMUNICATIONS",
                "country": "US",
            },
        ],
        "peers": [
            {
                "as_number": "AS6412",
                "description": "Gulfnet International KEMS LLC",
                "country": "KW",
            },
            {"as_number": "AS13335", "description": "Cloudflare Inc.", "country": "US"},
        ],
        "whois_response": "% [whois.apnic.net]\nas-block: AS17408 - AS17651\n",
    }
}


MOCK_SECURITY_DEDICATED = {
    "ip": "2.56.188.34",
    "security": {
        "threat_score": 80,
        "is_tor": False,
        "is_proxy": True,
        "proxy_provider_names": ["Zyte Proxy"],
        "proxy_confidence_score": 80,
        "proxy_last_seen": "2025-12-12",
        "is_residential_proxy": True,
        "is_vpn": True,
        "vpn_provider_names": ["Nord VPN"],
        "vpn_confidence_score": 80,
        "vpn_last_seen": "2026-01-19",
        "is_relay": False,
        "relay_provider_name": "",
        "is_anonymous": True,
        "is_known_attacker": True,
        "is_bot": False,
        "is_spam": False,
        "is_cloud_provider": True,
        "cloud_provider_name": "Packethub S.A.",
    },
}


MOCK_ABUSE_RESPONSE = {
    "ip": "8.8.8.8",
    "abuse": {
        "route": "8.8.8.0/24",
        "country": "",
        "name": "Abuse",
        "organization": "Abuse",
        "kind": "group",
        "address": "1600 Amphitheatre Parkway, Mountain View, CA 94043",
        "emails": ["network-abuse@google.com"],
        "phone_numbers": ["+1-650-253-0000"],
    },
}
