MIME_PDF = "application/pdf"
MIME_TXT = "text/plain"

RESULT_FORMAT_TYPE = "type"
RESULT_FORMAT_CATEGORY = "category"
RESULT_FORMAT_MATCH = "match"

ENTITY_CLASS = "entity"
OBSERVABLE_CLASS = "observable"

CONFIG_PATH = "filter_list"
COMMENT_INDICATOR = "#"

OBSERVABLE_DETECTION_CUSTOM_REGEX = "custom_regex"
OBSERVABLE_DETECTION_LIBRARY = "library"
OBSERVABLE_DETECTION_OPTIONS = [
    OBSERVABLE_DETECTION_LIBRARY,
    OBSERVABLE_DETECTION_CUSTOM_REGEX,
]
