version: '3'
services:
  connector-yara:
    image: opencti/connector-yara:latest
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=840210d2-cb25-4841-81c2-850b431918ee
      - CONNECTOR_NAME=YARA
      - CONNECTOR_SCOPE=Artifact # MIME type or Stix Object
      - CONNECTOR_AUTO=true
      - CONNECTOR_LOG_LEVEL=error
      #- YARA_TLP_LEVEL=clear
    restart: always
