services:
  dev-connector:
    build:
      context: ../external-import/${CONNECTOR_NAME}
      dockerfile: ../../docker-dev/Dockerfile
      args:
        CONNECTOR_NAME: ${CONNECTOR_NAME}
    volumes:
      - ../external-import/${CONNECTOR_NAME}/src:/opt/opencti-connector-${CONNECTOR_NAME}
      - ../external-import/${CONNECTOR_NAME}/tests:/opt/tests
    env_file:
      - ./secrets.env
      - ./connector.env
    entrypoint: ["sh"]