FROM redhat/ubi9-minimal

ENV PYTHONDONTWRITEBYTECODE=1

# Set environment variable
ENV CONNECTOR_TYPE=INTERNAL_EXPORT_FILE

# Set working directory
WORKDIR /opt/connector

# Copy the connector
COPY src /opt/connector

RUN set -eux; \
    microdnf -y --setopt=install_weak_deps=0 install -y python3.12 python3.12-pip git; \
    microdnf clean all

# Install Python dependencies
RUN pip3.12 install --no-cache-dir -r /opt/connector/requirements.txt

# Clean up unnecessary files
RUN microdnf clean all && \
    rm -rf /var/cache/yum && \
    rm -rf /root/.cache

CMD ["python3.12", "export-file-txt.py"]

