"""STIX 2.1 strict validation tests.

Validates every bundle generated by StixBuilder against the official
STIX 2.1 specification using stix2-validator. This catches:
- Invalid STIX object types or missing required properties
- Malformed deterministic IDs
- Invalid relationship source/target references
- Non-compliant timestamps, TLP markings, kill chains
"""

import json
import os
import sys

import pytest

SRC_DIR = os.path.join(os.path.dirname(__file__), os.pardir, "src")
sys.path.insert(0, os.path.abspath(SRC_DIR))

from connector.stix_builder import StixBuilder
from stix2validator import ValidationOptions, validate_string

# ── Fixtures ──────────────────────────────────────────────────────────────

ENTITY = {
    "type": "file",
    "spec_version": "2.1",
    "id": "file--00000000-0000-4000-8000-000000000001",
    "hashes": {"SHA-256": "a" * 64},
}

SCAN_DATA = {
    "score": 85,
    "family": "DTrack",
    "labels": ["backdoor"],
    "operating_systems": ["Windows"],
    "sha256": "a" * 64,
    "sha1": "b" * 40,
    "md5": "c" * 32,
    "hashes": {"MD5": "c" * 32, "SHA-256": "a" * 64},
    "detection_stats": {"malicious": 45, "total": 70},
    "engine_detections": [{"engine": "ClamAV", "family": "Backdoor.DTrack"}],
    "permalink": "https://polyswarm.network/scan/results/test",
    "first_seen": "2024-01-01T00:00:00Z",
    "last_seen": "2024-06-01T00:00:00Z",
    "extended_type": "PE32",
    "mimetype": "application/x-dosexec",
}

SANDBOX_DATA = {
    "provider": "triage",
    "score": 90,
    "family": "DTrack",
    "ttps": ["T1055", "T1082"],
    "labels": ["backdoor"],
    "signatures": ["injects_code"],
    "domains": [{"domain": "evil.c2.io"}],
    "ips": ["203.0.113.1"],
    "c2_candidates": [{"ip": "203.0.113.1", "port": 443, "reason": "C2"}],
    "permalink": "https://polyswarm.network/sandbox/results/test",
}

CONFIG = {
    "create_indicators": True,
    "create_observables": True,
    "min_polyscore": 50,
    "replace_with_lower_score": True,
}


class StubHelper:
    """Minimal OpenCTIConnectorHelper stand-in for testing."""

    connect_scope = "Artifact"
    connector_logger = type(
        "_L",
        (),
        {
            "info": lambda s, *a, **k: None,
            "warning": lambda s, *a, **k: None,
            "error": lambda s, *a, **k: None,
            "debug": lambda s, *a, **k: None,
        },
    )()

    def log_info(self, msg):
        pass

    def log_warning(self, msg):
        pass

    def log_error(self, msg):
        pass

    def log_debug(self, msg):
        pass


@pytest.fixture
def builder():
    return StixBuilder(helper=StubHelper())


# ── STIX 2.1 Validation ──────────────────────────────────────────────────


def _validate_bundle(objects):
    """Build a STIX bundle from objects and validate against STIX 2.1 spec."""
    bundle = {
        "type": "bundle",
        "id": "bundle--00000000-0000-4000-8000-000000000099",
        "objects": objects,
    }
    bundle_str = json.dumps(bundle)
    # Use lenient options since OpenCTI adds custom properties (x_opencti_*)
    opts = ValidationOptions(strict=False)
    results = validate_string(bundle_str, opts)
    return results


class TestSTIXBundleValidation:
    """Validate generated bundles against STIX 2.1 specification."""

    def test_scan_only_bundle_valid(self, builder):
        objects = builder.build_bundle(
            entity=ENTITY, scan_data=SCAN_DATA, config=CONFIG
        )
        assert len(objects) > 0, "Bundle should not be empty"
        results = _validate_bundle(objects)
        assert (
            results.is_valid
        ), f"STIX validation errors: {[str(e) for e in results.errors]}"

    def test_sandbox_only_bundle_valid(self, builder):
        objects = builder.build_bundle(
            entity=ENTITY, sandbox_data=SANDBOX_DATA, config=CONFIG
        )
        assert len(objects) > 0
        results = _validate_bundle(objects)
        assert (
            results.is_valid
        ), f"STIX validation errors: {[str(e) for e in results.errors]}"

    def test_combined_bundle_valid(self, builder):
        objects = builder.build_bundle(
            entity=ENTITY, scan_data=SCAN_DATA, sandbox_data=SANDBOX_DATA, config=CONFIG
        )
        assert len(objects) > 0
        results = _validate_bundle(objects)
        assert (
            results.is_valid
        ), f"STIX validation errors: {[str(e) for e in results.errors]}"

    def test_error_note_valid(self, builder):
        note = builder.create_error_note(
            ENTITY, "Test Error", "Something went wrong", ["Fix it"]
        )
        results = _validate_bundle([note])
        assert (
            results.is_valid
        ), f"STIX validation errors: {[str(e) for e in results.errors]}"


class TestSTIXDeterministicIDs:
    """Verify that identical inputs produce identical STIX IDs."""

    def test_author_id_stable(self):
        b1 = StixBuilder(helper=StubHelper())
        b2 = StixBuilder(helper=StubHelper())
        assert b1.author_id == b2.author_id

    def test_note_id_stable(self, builder):
        id1 = builder._note_id("artifact--test", "scan-summary")
        id2 = builder._note_id("artifact--test", "scan-summary")
        assert id1 == id2

    def test_malware_id_stable(self):
        b1 = StixBuilder(helper=StubHelper())
        b2 = StixBuilder(helper=StubHelper())
        objs1 = b1.build_bundle(entity=ENTITY, scan_data=SCAN_DATA, config=CONFIG)
        objs2 = b2.build_bundle(entity=ENTITY, scan_data=SCAN_DATA, config=CONFIG)
        mal1 = [o for o in objs1 if o.get("type") == "malware"]
        mal2 = [o for o in objs2 if o.get("type") == "malware"]
        if mal1 and mal2:
            assert mal1[0]["id"] == mal2[0]["id"]


class TestSTIXRelationshipIntegrity:
    """Verify all relationships reference valid objects in the bundle."""

    def test_all_relationship_refs_exist(self, builder):
        objects = builder.build_bundle(
            entity=ENTITY, scan_data=SCAN_DATA, sandbox_data=SANDBOX_DATA, config=CONFIG
        )
        obj_ids = {o.get("id") for o in objects if o.get("id")}
        relationships = [o for o in objects if o.get("type") == "relationship"]
        for rel in relationships:
            src = rel.get("source_ref")
            tgt = rel.get("target_ref")
            assert (
                src in obj_ids
            ), f"Relationship {rel['id']} references missing source: {src}"
            assert (
                tgt in obj_ids
            ), f"Relationship {rel['id']} references missing target: {tgt}"

    def test_no_duplicate_ids_in_bundle(self, builder):
        objects = builder.build_bundle(
            entity=ENTITY, scan_data=SCAN_DATA, sandbox_data=SANDBOX_DATA, config=CONFIG
        )
        ids = [o.get("id") for o in objects if o.get("id")]
        dupes = [i for i in ids if ids.count(i) > 1]
        assert len(dupes) == 0, f"Duplicate IDs in bundle: {set(dupes)}"

    def test_all_objects_have_type(self, builder):
        objects = builder.build_bundle(
            entity=ENTITY, scan_data=SCAN_DATA, sandbox_data=SANDBOX_DATA, config=CONFIG
        )
        for obj in objects:
            assert "type" in obj, f"Object missing 'type': {obj.get('id', 'unknown')}"

    def test_created_by_refs_valid(self, builder):
        objects = builder.build_bundle(
            entity=ENTITY, scan_data=SCAN_DATA, config=CONFIG
        )
        obj_ids = {o.get("id") for o in objects}
        # ``created_by_ref`` is only valid on SDOs / SROs — STIX 2.1
        # SCOs (domain-name, ipv4-addr, url, ...) MUST carry the
        # author via the OpenCTI extension ``x_opencti_created_by_ref``.
        # Validate whichever key is present and pin that SCOs never
        # use ``created_by_ref`` (which would break strict STIX
        # validation when the platform re-emits the bundle).
        # Note: the type list is the union of every observable type
        # actually emitted by ``stix_builder``; it does not need to be
        # exhaustive across STIX 2.1.
        sco_types = {
            "artifact",
            "autonomous-system",
            "directory",
            "domain-name",
            "email-addr",
            "email-message",
            "file",
            "ipv4-addr",
            "ipv6-addr",
            "mac-addr",
            "mutex",
            "network-traffic",
            "process",
            "software",
            "url",
            "user-account",
            "windows-registry-key",
            "x509-certificate",
        }
        for obj in objects:
            cbr = obj.get("created_by_ref")
            if cbr:
                assert obj.get("type") not in sco_types, (
                    f"SCO {obj['id']} carries ``created_by_ref`` — observables "
                    f"must use ``x_opencti_created_by_ref`` instead"
                )
                assert (
                    cbr in obj_ids
                ), f"Object {obj['id']} has invalid created_by_ref: {cbr}"
            x_cbr = obj.get("x_opencti_created_by_ref")
            if x_cbr:
                assert obj.get("type") in sco_types, (
                    f"Non-SCO {obj['id']} uses ``x_opencti_created_by_ref`` — "
                    f"SDOs/SROs must use ``created_by_ref`` instead"
                )
                assert (
                    x_cbr in obj_ids
                ), f"Object {obj['id']} has invalid x_opencti_created_by_ref: {x_cbr}"
