services:
  connector-ctm360-hackerview-feed:
    image: opencti/connector-ctm360-hackerview:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_CTM360_HACKERVIEW_FEED_ID}
      - CONNECTOR_NAME=CTM360-HackerView
      - CONNECTOR_SCOPE=CTM360-HackerView
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_DURATION_PERIOD=PT24H
      - CTM360_HACKERVIEW_FEED_API_BASE_URL=https://hackerview.ctm360.com
      - CTM360_HACKERVIEW_FEED_API_KEY=${CTM360_HACKERVIEW_FEED_API_KEY}
      - CTM360_HACKERVIEW_FEED_IMPORT_ISSUES=true
      - CTM360_HACKERVIEW_FEED_IMPORT_RESOLVED_ISSUES=true
      - CTM360_HACKERVIEW_FEED_IMPORT_DOMAIN_ASSETS=true
      - CTM360_HACKERVIEW_FEED_IMPORT_HOST_ASSETS=true
      - CTM360_HACKERVIEW_FEED_IMPORT_IP_ASSETS=true
      - CTM360_HACKERVIEW_FEED_ENABLE_STATUS_TRACKING=true
      - CTM360_HACKERVIEW_FEED_STATUS_POLL_INTERVAL=PT1H
    restart: always

