MIME_PDF = "application/pdf"
MIME_TXT = "text/plain"
MIME_HTML = "text/html"
MIME_CSV = "text/csv"
MIME_MD = "text/markdown"

RESULT_FORMAT_TYPE = "type"
RESULT_FORMAT_CATEGORY = "category"
RESULT_FORMAT_MATCH = "match"
RESULT_FORMAT_RANGE = "range"

ENTITY_CLASS = "entity"
OBSERVABLE_CLASS = "observable"

CONFIG_PATH = "filter_list"
COMMENT_INDICATOR = "#"

OBSERVABLE_DETECTION_CUSTOM_REGEX = "custom_regex"
OBSERVABLE_DETECTION_LIBRARY = "library"
OBSERVABLE_DETECTION_OPTIONS = [
    OBSERVABLE_DETECTION_LIBRARY,
    OBSERVABLE_DETECTION_CUSTOM_REGEX,
]

ANALYSIS_TYPE = "mapping_analysis"
