spl_indicators = [
    {
        "id": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "spec_version": "2.1",
        "identity_class": "organization",
        "name": "Splunk",
        "description": "Splunk Inc. is a U.S.-based software company specializing in data analytics, cybersecurity, observability, and machine learning. Best known for its flagship platform that enables organizations to search, monitor, and analyze machine-generated data in real time, Splunk is widely adopted across the security industry for Security Information and Event Management (SIEM), threat detection, incident response, and IT operations. Splunk\u2019s technology helps organizations gain operational intelligence, enhance system reliability, and strengthen their cybersecurity posture.",
        "contact_information": "https://www.splunk.com\nhttps://github.com/splunk/security_content",
        "created": "2025-01-01T00:00:00.000Z",
        "modified": "2025-07-28T14:35:51.873Z",
        "x_opencti_organization_type": "vendor",
        "x_opencti_reliability": "A - Completely reliable",
        "x_opencti_id": "d2e74733-7a5a-49de-b197-d68a4dc9811b",
        "x_opencti_type": "Organization",
        "type": "identity",
    },
    {
        "id": "indicator--88ef1bc8-71d1-566d-b0e7-0db708dbc3ac",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-07-29T17:34:36.589Z",
        "modified": "2025-07-29T17:34:36.658Z",
        "pattern_type": "spl",
        "pattern": '| tstats earliest(_time) AS e_time\nlatest(_time) AS l_time\nsum(Web.bytes) AS total_bytes\nsum(Web.bytes_in) AS total_bytes_in\nsum(Web.bytes_out) AS total_bytes_out\nvalues(Web.category) AS category\nvalues(Web.http_user_agent) AS http_user_agent\nvalues(Web.http_referrer) AS http_referrer\nvalues(nodename) AS nodename\ncount \nfrom datamodel=Web \nwhere index=* \nWeb.url IN ("<DOMAIN_LIST>")\nAND NOT Web.dest IN ("10.0.0.0/8","172.16.0.0/12","192.168.0.0/16") \nby _time sourcetype index Web.src Web.action Web.url  span=1d \n| rename "Web.*" as * _time AS time index AS index sourcetype AS sourcetype\n| eval _domain_field=lower(url), _domain_list="mozilla" \n| lookup ut_parse_extended_lookup url as _domain_field list as _domain_list \n| spath input=ut_subdomain_parts \n| fields - ut_subdomain_parts \n| eval domain=ut_domain, fqdn=ut_netloc \n| eval action=coalesce(action,"unknown")\n| appendpipe \n    [ stats count \n    | where count == 0 \n    | fillnull value="N/A" nodename sourcetype index e_time l_time src action category http_referrer http_user_agent total_bytes total_bytes_in total_bytes_out\n    | eval fqdn="No Results"]\n| table nodename sourcetype index e_time l_time src fqdn action category http_referrer http_user_agent total_bytes total_bytes_in total_bytes_out count',
        "name": "Outbound Domain Indicator match in Web Traffic",
        "description": "This indicator represents a Splunk detection query designed to identify outbound web traffic to a predefined list of suspicious or monitored domains. The query leverages the `Web` data model in Splunk and analyzes HTTP traffic over a 28-day period. Internal destinations (RFC1918 IP ranges) are excluded to focus on external traffic of interest.\n\nThe detection extracts and enriches key metadata such as domain names, fully qualified domain names (FQDN), HTTP user agents, referrers, and byte-level traffic statistics. It uses a custom domain parsing lookup (`ut_parse_extended_lookup`) to normalize domain data for more consistent threat correlation and analysis.\n\n**Use Case:**  \nSupports threat hunting, detection engineering, and investigations by highlighting systems or users making connections to potentially risky domains. This can indicate command-and-control attempts, phishing callbacks, or policy violations.\n\n**Data Source:**  \n- Splunk (Web Data Model, accelerated summaries)\n\n**Key Fields Captured:**  \n- `url`, `fqdn`, `domain`  \n- `src`, `action`, `category`, `http_user_agent`, `http_referrer`  \n- `total_bytes`, `total_bytes_in`, `total_bytes_out`  \n- `sourcetype`, `index`, `nodename`, `timestamp`",
        "indicator_types": ["anomalous-activity"],
        "valid_from": "2025-07-29T17:34:36.343Z",
        "valid_until": "2030-12-30T23:59:00.006Z",
        "x_mitre_platforms": ["URL Filtering", "Web"],
        "x_opencti_score": 40,
        "x_opencti_detection": True,
        "x_opencti_main_observable_type": "Domain-Name",
        "labels": ["threat-hunting-splunk"],
        "kill_chain_phases": [
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "collection",
                "x_opencti_order": 10,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "command-and-control",
                "x_opencti_order": 11,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "exfiltration",
                "x_opencti_order": 12,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "initial-access",
                "x_opencti_order": 2,
            },
        ],
        "x_opencti_id": "0fae4151-b101-41cf-aff2-f71d0139c820",
        "x_opencti_type": "Indicator",
        "type": "indicator",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"
        ],
    },
    {
        "id": "indicator--c94e77f2-15e3-5695-aa1b-dc2ddc5c0e12",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-07-28T14:22:53.444Z",
        "modified": "2025-07-28T15:26:29.834Z",
        "pattern_type": "spl",
        "pattern": '| tstats\nearliest(_time) AS e_time \nlatest(_time) AS l_time \nsum(All_Traffic.bytes) as total_bytes \nsum(All_Traffic.bytes_out) as total_bytes_out\nsum(All_Traffic.bytes_in) as total_bytes_in\nvalues(All_Traffic.src_port) as src_port \nvalues(All_Traffic.dest_port) as dest_port \nvalues(All_Traffic.direction) AS direction\nvalues(All_Traffic.user) AS user\nvalues(All_Traffic.app) AS app\ndc(All_Traffic.dest_port) AS distinct_dest_ports\ncount \nfrom datamodel=Network_Traffic \nwhere index=* \nAll_Traffic.dest IN ("<IP_LIST>")\nnodename="All_Traffic"\nby _time sourcetype index All_Traffic.dest All_Traffic.src All_Traffic.action span=1d\n| rename "All_Traffic.*" as * sourcetype AS sourcetype index AS index\n| eval dest_port=if(distinct_dest_ports>10,mvappend(mvindex(dest_port,0,5),"..."),dest_port)\n| fillnull value="-"\n| appendpipe\n    [stats count\n    | where count == 0\n    | fillnull value="N/A" sourcetype index l_time e_time src app user action direction total_bytes total_bytes_in total_bytes_out src_port dest_port count\n    | fillnull value="No Results" dest]\n| eval observable_value=dest\n| eval indicator_id="<INDICATOR_ID>"\n| table sourcetype index e_time l_time src src_port dest dest_port app user action direction total_bytes total_bytes_in total_bytes_out count ref_id indicator_id observable_value',
        "name": "Outbound Traffic to IP Address list",
        "description": "## Overview\n\nThis Splunk search is focused on analyzing network traffic patterns over a specified period. It aggregates and summarizes data from the \u201cNetwork_Traffic\u201d datamodel, providing insights into traffic volume, direction, and key metadata.  The search is designed to identify and analyze network traffic activity, capturing details such as bytes transferred, user interactions, application usage, and network ports over the last 30 days.\n\n**Data Source**: It utilizes the Network_Traffic data model, analyzing traffic from the ALL_Traffic dataset.\n\n**Timeframe**: The search spans a period of 30 days, allowing a comprehensive look at historical traffic patterns.\n\n### Key Metrics and Fields:\n\n**Traffic Aggregation**: The search sums up bytes transferred both inbound and outbound (total_bytes, total_bytes_in, total_bytes_out), providing a clear view of overall data movement.\n\n**Field Values Extraction**: It extracts values for src_port, dest_port, user, app, and direction to help pinpoint who is generating the traffic, which applications are in use, and the direction of the data flow.\n\n**Distinct Count**: It calculates the distinct number of destination ports (distinct_dest_ports) to understand the variety of endpoints being accessed.\n\n**Traffic Categorization**: Uses sourcetype, sourcetype, and index to differentiate the types of traffic and their respective indices, aiding in data organization and filtering.\n\n### Output Processing:\n\n**Mapping and Transformation**: It maps distinct ports to a maximum of 10 for simplified analysis and renames fields for consistency (e.g., ALL_Traffic.*).\n\n**Refinement**: Uses fillnull commands to replace missing data with placeholders, ensuring that empty fields are accounted for in the results.\n\n**Output Format**: The final table displays critical traffic details such as time, source, destination, user, action, direction, and byte counts, offering a detailed summary of network interactions.\n\n### Use Case:\n\nThis search can be used for investigating abnormal traffic patterns, potential data exfiltration, or unusual application usage across a network. The summarized data helps identify deviations from normal behavior, making it valuable for threat detection and analysis.",
        "indicator_types": ["anomalous-activity"],
        "valid_from": "2025-07-28T14:22:53.216Z",
        "valid_until": "2030-12-30T23:59:00.006Z",
        "x_opencti_score": 23,
        "x_opencti_detection": False,
        "x_opencti_main_observable_type": "IPv4-Addr",
        "x_mitre_platforms": ["Network Devices"],
        "labels": ["threat-hunting-splunk"],
        "kill_chain_phases": [
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "exfiltration",
                "x_opencti_order": 12,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "initial-access",
                "x_opencti_order": 2,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "lateral-movement",
                "x_opencti_order": 9,
            },
        ],
        "x_opencti_id": "249e497e-ce21-4c6b-b73d-d2a170d544ad",
        "x_opencti_type": "Indicator",
        "type": "indicator",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"
        ],
    },
    {
        "id": "indicator--1f9b0afe-8455-50f2-947b-66143dca7800",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-07-28T15:18:30.151Z",
        "modified": "2025-07-28T15:18:30.218Z",
        "pattern_type": "spl",
        "pattern": '| tstats   \nearliest(_time) AS e_time \nlatest(_time) AS l_time \nsum(All_Traffic.bytes) as total_bytes \nsum(All_Traffic.bytes_out) as total_bytes_out\nsum(All_Traffic.bytes_in) as total_bytes_in\nvalues(All_Traffic.src_port) as src_port \nvalues(All_Traffic.dest_port) as dest_port \nvalues(All_Traffic.direction) AS direction\nvalues(All_Traffic.user) AS user\nvalues(All_Traffic.app) AS app\ndc(All_Traffic.src_port) AS distinct_src_ports\ncount \nfrom datamodel=Network_Traffic \nwhere index=*\nAll_Traffic.src IN (<IP_LIST>)\nnodename="All_Traffic"\nby _time sourcetype index All_Traffic.dest All_Traffic.src All_Traffic.action span=1m\n| rename "All_Traffic.*" as * sourcetype AS sourcetype index AS index\n| eval src_port=if(distinct_src_ports>10,mvappend(mvindex(src_port,0,5),"..."),src_port)\n| fillnull value="-"\n| appendpipe\n    [stats count\n    | where count == 0\n    | fillnull value="N/A" sourcetype index l_time e_time src app user action direction total_bytes total_bytes_in total_bytes_out src_port dest_port count\n    | fillnull value="No Results" src]\n| eval observable_value=src\n| eval indicator_id="<INDICATOR_ID>"\n| table sourcetype index e_time l_time src src_port dest dest_port app user action direction total_bytes total_bytes_in total_bytes_out count indicator_id observable_value',
        "name": "Inbound Network Traffic from IP List",
        "description": "## Overview\n\nThis Splunk search is focused on identifying **inbound network traffic** originating from a predefined list of suspicious or high-risk IP addresses. It leverages the `Network_Traffic` data model to aggregate and summarize activity over a 30-day period, highlighting potential threats and enabling security analysts to investigate unsolicited or anomalous external communication.\n\n**Data Source**: The search queries the `Network_Traffic` data model, analyzing traffic from the `All_Traffic` dataset.\n\n**Timeframe**: It captures events over the last 30 days, enabling retrospective analysis of inbound communication attempts.\n\n### Key Metrics and Fields\n\n**Traffic Aggregation**:  \nIt computes the total amount of data transferred (`total_bytes`), as well as the directional breakdown (`total_bytes_in` and `total_bytes_out`), offering visibility into how much data was received from external sources.\n\n**Field Values Extraction**:  \nIt extracts values for `src_port`, `dest_port`, `user`, `app`, and `direction`, providing insight into which ports and applications were targeted, and who or what was involved on the internal network.\n\n**Distinct Count**:  \nThe search calculates the number of distinct source ports (`distinct_src_ports`) used by the external IPs, which can indicate port scanning, evasion, or probing activity.\n\n**Traffic Categorization**:  \nIt includes `sourcetype`, `sourcetype`, and `index` to contextualize traffic types and assist with filtering and triage.\n\n### Output Processing\n\n**Mapping and Transformation**:  \nThe search maps and limits the number of displayed source ports for readability, and standardizes field names by renaming `All_Traffic.*` fields.\n\n**Refinement**:  \nIt uses `fillnull` to handle missing data gracefully, ensuring a consistent and complete output even if some fields are not populated.\n\n**Output Format**:  \nThe resulting table displays detailed traffic records including time, source, destination, user, direction, action, and byte counts, forming a clear picture of inbound interactions from external sources.\n\n### Use Case\n\nThis search is ideal for monitoring and detecting potential threats from known or suspected adversary infrastructure. It supports investigations into command-and-control attempts, targeted scanning, or early stages of compromise. By correlating inbound traffic against a curated IP list, this detection enhances threat visibility and provides actionable intelligence.",
        "indicator_types": ["anomalous-activity"],
        "valid_from": "2025-07-28T15:18:29.921Z",
        "valid_until": "2030-12-30T23:59:00.006Z",
        "x_opencti_score": 23,
        "x_opencti_detection": True,
        "x_opencti_main_observable_type": "IPv4-Addr",
        "x_mitre_platforms": ["Network Devices"],
        "labels": ["threat-hunting-splunk"],
        "kill_chain_phases": [
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "command-and-control",
                "x_opencti_order": 11,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "discovery",
                "x_opencti_order": 8,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "initial-access",
                "x_opencti_order": 2,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "reconnaissance",
                "x_opencti_order": 0,
            },
        ],
        "x_opencti_id": "e4f1a53e-4f79-4758-bd31-f4efc489e749",
        "x_opencti_type": "Indicator",
        "type": "indicator",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"
        ],
    },
    {
        "id": "indicator--5a1a3039-8dcc-55e1-bfbb-811f25e2c0a6",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-07-29T17:39:28.353Z",
        "modified": "2025-07-29T17:39:28.443Z",
        "pattern_type": "spl",
        "pattern": '| tstats earliest(_time) AS e_time\nlatest(_time) AS l_time\nvalues(DNS.record_type) AS record_type\nvalues(DNS.dest_category) AS category\nvalues(nodename) AS nodename\ncount \nfrom \ndatamodel=Network_Resolution \nwhere DNS.query IN (<HOSTNAME_LIST>) \nDNS.src!="in-addr.arpa" DNS.src!="None" \nby _time sourcetype index DNS.src DNS.query  span=1d \n| rename "DNS.*" as * _time AS time index AS index sourcetype AS sourcetype\n| eval _domain_field=lower(query), _domain_list="mozilla" \n| lookup ut_parse_extended_lookup url as _domain_field list as _domain_list \n| spath input=ut_subdomain_parts \n| fields - ut_subdomain_parts \n| eval domain=ut_domain, fqdn=ut_netloc \n| eval action=coalesce(action,"unknown")\n| appendpipe \n    [ stats count \n    | where count == 0 \n    | fillnull value="N/A" e_time l_time record_type category nodename src sourcetype index count\n    | eval fqdn="No Results"]\n| table nodename index sourcetype e_time l_time src fqdn record_type category count',
        "name": "Outbound Hostname Indicator match in DNS queries",
        "description": 'This indicator represents a Splunk detection query that identifies DNS resolution activity to a predefined list of hostnames associated with suspicious, monitored, or potentially malicious infrastructure. The query leverages the `Network_Resolution` data model and aggregates DNS activity over a 1-day span across a 28-day historical window.\n\nThe search filters out internal and non-relevant sources (`in-addr.arpa`, `"None"`), then extracts and enriches key fields including domain, FQDN, record type, and destination categories. Domain parsing is handled via the `ut_parse_extended_lookup` enrichment to normalize DNS queries and provide structured observables for further analysis.\n\n**Use Case:**  \nSupports threat hunting and incident response workflows by highlighting systems performing suspicious DNS lookups \u2014 potentially indicating command-and-control (C2) activity, domain generation algorithm (DGA) behavior, phishing link resolution, or reconnaissance via DNS.\n\n**Data Source:**  \n- Splunk (Network_Resolution Data Model)\n\n**Key Fields Captured:**  \n- `query`, `fqdn`, `domain`  \n- `src`, `record_type`, `category`, `nodename`  \n- `sourcetype`, `index`, `timestamp`, `count`',
        "indicator_types": ["anomalous-activity"],
        "valid_from": "2025-07-29T17:39:28.131Z",
        "valid_until": "2030-12-30T23:59:00.006Z",
        "x_opencti_score": 40,
        "x_opencti_detection": True,
        "x_opencti_main_observable_type": "Domain-Name",
        "x_mitre_platforms": ["Directory Services"],
        "labels": ["threat-hunting-splunk"],
        "kill_chain_phases": [
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "command-and-control",
                "x_opencti_order": 11,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "discovery",
                "x_opencti_order": 8,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "exfiltration",
                "x_opencti_order": 12,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "initial-access",
                "x_opencti_order": 2,
            },
        ],
        "x_opencti_id": "38ffd602-8420-4479-8684-d34239ffc2dc",
        "x_opencti_type": "Indicator",
        "type": "indicator",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"
        ],
    },
    {
        "id": "indicator--1c641561-d89a-5804-84d9-cdb5f18ea32b",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-07-29T17:46:17.384Z",
        "modified": "2025-07-29T17:46:17.454Z",
        "pattern_type": "spl",
        "pattern": '| tstats     values(Filesystem.user) as user\n    values(Filesystem.dest) as dest\n    values(Filesystem.file_name) as file_name\n    values(Filesystem.file_path) as file_path\n    values(Filesystem.file_hash) as file_hash\n    from datamodel=Endpoint.Filesystem\n    where Filesystem.file_hash IN ("<FILE_HASH_LIST>")\n    by _time, Filesystem.file_hash\n| rename Filesystem.* as *\n| append [\n    | tstats         values(Malware_Attacks.signature) as signature\n        values(Malware_Attacks.file_name) as file_name\n        values(Malware_Attacks.file_path) as file_path\n        values(Malware_Attacks.file_hash) as file_hash\n        values(Malware_Attacks.dest) as dest\n        values(Malware_Attacks.user) as user\n        from datamodel=Malware\n        where Malware_Attacks.file_hash IN ("<FILE_HASH_LIST>")\n        by _time, Malware_Attacks.file_hash\n    | rename Malware_Attacks.* as *\n]\n| fillnull value="N/A"\n| table _time file_hash file_name file_path user dest signature\n| sort - _time',
        "name": "File Hash Detected",
        "description": "**Description:**  \nThis indicator represents the detection of file hashes associated with potentially malicious or unauthorized activity. The query analyzes both the `Endpoint.Filesystem` and `Malware` data models in Splunk to identify files that match known or suspicious hashes. It captures contextual metadata including file name, path, user, destination host, and malware signatures (if available), helping to determine how and where the file was observed within the environment.\n\nThe detection supports correlation between filesystem activity and malware alerts, enabling security teams to investigate presence, propagation, or execution of known malicious files.\n\n**Data Sources:**  \n- Splunk (Endpoint.Filesystem Data Model)  \n- Splunk (Malware Data Model)\n\n**Use Case:**  \nThis search supports incident response, digital forensics, and threat hunting efforts by identifying systems that have encountered known bad files. It helps answer key questions like:  \n- Has this file been seen in our environment?  \n- Which users or hosts were involved?  \n- Was it detected by our malware defenses?\n\nThe output provides actionable intelligence for containment, remediation, and broader compromise assessment.",
        "indicator_types": ["malicious-activity"],
        "valid_from": "2025-07-29T17:46:17.141Z",
        "valid_until": "2030-12-30T23:59:00.006Z",
        "x_opencti_score": 40,
        "x_opencti_detection": True,
        "x_opencti_main_observable_type": "StixFile",
        "x_mitre_platforms": ["Windows", "EDR"],
        "labels": ["threat-hunting-splunk"],
        "kill_chain_phases": [
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "collection",
                "x_opencti_order": 10,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "defense-evasion",
                "x_opencti_order": 6,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "execution",
                "x_opencti_order": 3,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "impact",
                "x_opencti_order": 13,
            },
            {
                "kill_chain_name": "mitre-attack",
                "phase_name": "persistence",
                "x_opencti_order": 4,
            },
        ],
        "x_opencti_id": "3a89b315-e32b-476e-9a9d-bdc2cb8f0872",
        "x_opencti_type": "Indicator",
        "type": "indicator",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--f88d31f6-486f-44da-b317-01333bde0b82"
        ],
    },
    {
        "id": "note--b9b93bc8-16e4-5711-b3bf-1a96377870eb",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-08-04T19:18:09.000Z",
        "modified": "2025-08-04T19:22:02.021Z",
        "content": '{\n  "earliest_time": "-30d@d",\n  "latest_time": "now",\n  "timeout": 60,\n  "wait_seconds": 2\n}',
        "note_types": ["Search Parameters"],
        "likelihood": 50,
        "external_references": [
            {
                "source_name": "Splunk",
                "url": "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTsearch?_gl=1*1usx40f*_gcl_au*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*FPAU*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*_ga*MTcxNjI0NTk4LjE3Mzg4NjE1MDA.*_ga_5EPM2P39FV*czE3NTQzMzMwNDgkbzEwMSRnMSR0MTc1NDMzNTI0MiRqNjAkbDAkaDE2NTE5NTM0NDM.*_fplc*cUxKN2FoY2gycnVMUkNlJTJCWkRyQ0tqR0klMkJuUnJXNm1mUmpvViUyRkMwaGRCY0Rvck44ZzJKWWZjS1cxY2FLNXZkJTJGeXlWclJ0bnFJcCUyQkxWakc4VklIcUNHYVhkM0lTQ0gwRUVrUFZwMUl1ekNRMlZVdFJsYTR5Y0NyeVFYSFNVdyUzRCUzRA..#search.2Fjobs",
                "external_id": "Search/Job Parameters",
            }
        ],
        "x_opencti_id": "ef986557-1498-4a9b-a203-03c31019da1a",
        "x_opencti_type": "Note",
        "type": "note",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da"
        ],
        "object_refs": [
            "indicator--56bff783-ffae-550e-9b6a-d68a3f69aeb4",
            "indicator--1f9b0afe-8455-50f2-947b-66143dca7800",
            "indicator--88ef1bc8-71d1-566d-b0e7-0db708dbc3ac",
        ],
        "abstract": "Last 30 Days",
    },
    {
        "id": "note--c004b7b2-8bd9-5351-98bc-0f786a0ec270",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-08-04T19:18:09.000Z",
        "modified": "2025-08-04T19:22:02.021Z",
        "content": '{\n  "earliest_time": "-90d@d",\n  "latest_time": "now",\n  "timeout": 60,\n  "wait_seconds": 2\n}',
        "note_types": ["Search Parameters"],
        "likelihood": 50,
        "external_references": [
            {
                "source_name": "Splunk",
                "url": "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTsearch?_gl=1*1usx40f*_gcl_au*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*FPAU*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*_ga*MTcxNjI0NTk4LjE3Mzg4NjE1MDA.*_ga_5EPM2P39FV*czE3NTQzMzMwNDgkbzEwMSRnMSR0MTc1NDMzNTI0MiRqNjAkbDAkaDE2NTE5NTM0NDM.*_fplc*cUxKN2FoY2gycnVMUkNlJTJCWkRyQ0tqR0klMkJuUnJXNm1mUmpvViUyRkMwaGRCY0Rvck44ZzJKWWZjS1cxY2FLNXZkJTJGeXlWclJ0bnFJcCUyQkxWakc4VklIcUNHYVhkM0lTQ0gwRUVrUFZwMUl1ekNRMlZVdFJsYTR5Y0NyeVFYSFNVdyUzRCUzRA..#search.2Fjobs",
                "external_id": "Search/Job Parameters",
            }
        ],
        "x_opencti_id": "ef986557-1498-4a9b-a203-03c31019da1a",
        "x_opencti_type": "Note",
        "type": "note",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da"
        ],
        "object_refs": [
            "indicator--1c641561-d89a-5804-84d9-cdb5f18ea32b",
        ],
        "abstract": "Last 90 Days",
    },
    {
        "id": "note--748be3a5-e08f-530d-8a5d-58c512c1fc4b",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-09-03T15:23:46.000Z",
        "modified": "2025-09-03T15:24:23.030Z",
        "content": '{ "earliest_time": "0", "latest_time": "now", "timeout": 60, "wait_seconds": 2 }',
        "note_types": ["Search Parameters"],
        "likelihood": 50,
        "external_references": [
            {
                "source_name": "Splunk",
                "url": "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTsearch?_gl=1*1usx40f*_gcl_au*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*FPAU*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*_ga*MTcxNjI0NTk4LjE3Mzg4NjE1MDA.*_ga_5EPM2P39FV*czE3NTQzMzMwNDgkbzEwMSRnMSR0MTc1NDMzNTI0MiRqNjAkbDAkaDE2NTE5NTM0NDM.*_fplc*cUxKN2FoY2gycnVMUkNlJTJCWkRyQ0tqR0klMkJuUnJXNm1mUmpvViUyRkMwaGRCY0Rvck44ZzJKWWZjS1cxY2FLNXZkJTJGeXlWclJ0bnFJcCUyQkxWakc4VklIcUNHYVhkM0lTQ0gwRUVrUFZwMUl1ekNRMlZVdFJsYTR5Y0NyeVFYSFNVdyUzRCUzRA..#search.2Fjobs",
                "external_id": "Search/Job Parameters",
            }
        ],
        "x_opencti_id": "eb1ce62a-093b-4b2e-a99f-38739aeac521",
        "x_opencti_type": "Note",
        "type": "note",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da"
        ],
        "abstract": "All Time",
    },
    {
        "id": "note--4984f686-67f8-519b-ad84-eec9fd0020eb",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-09-03T15:21:14.000Z",
        "modified": "2025-09-03T15:23:11.648Z",
        "content": '{ "earliest_time": "-7d@d", "latest_time": "now", "timeout": 60, "wait_seconds": 2 }',
        "note_types": ["Search Parameters"],
        "likelihood": 50,
        "external_references": [
            {
                "source_name": "Splunk",
                "url": "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTsearch?_gl=1*1usx40f*_gcl_au*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*FPAU*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*_ga*MTcxNjI0NTk4LjE3Mzg4NjE1MDA.*_ga_5EPM2P39FV*czE3NTQzMzMwNDgkbzEwMSRnMSR0MTc1NDMzNTI0MiRqNjAkbDAkaDE2NTE5NTM0NDM.*_fplc*cUxKN2FoY2gycnVMUkNlJTJCWkRyQ0tqR0klMkJuUnJXNm1mUmpvViUyRkMwaGRCY0Rvck44ZzJKWWZjS1cxY2FLNXZkJTJGeXlWclJ0bnFJcCUyQkxWakc4VklIcUNHYVhkM0lTQ0gwRUVrUFZwMUl1ekNRMlZVdFJsYTR5Y0NyeVFYSFNVdyUzRCUzRA..#search.2Fjobs",
                "external_id": "Search/Job Parameters",
            }
        ],
        "x_opencti_id": "5c0a62e1-d955-4fa2-86fb-6d1487dab725",
        "x_opencti_type": "Note",
        "type": "note",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da"
        ],
        "abstract": "Last 7 days",
    },
    {
        "id": "note--56248591-b7a0-59df-8bb5-eb0c6de2a72b",
        "spec_version": "2.1",
        "revoked": False,
        "confidence": 100,
        "created": "2025-09-03T15:17:41.000Z",
        "modified": "2025-09-03T15:20:52.027Z",
        "content": '{ "earliest_time": "-24h@h", "latest_time": "now", "timeout": 60, "wait_seconds": 2 }',
        "note_types": ["Search Parameters"],
        "likelihood": 50,
        "external_references": [
            {
                "source_name": "Splunk",
                "url": "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTsearch?_gl=1*1usx40f*_gcl_au*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*FPAU*MTMxNzQ1MDI1NS4xNzQ2NzE2MTk2*_ga*MTcxNjI0NTk4LjE3Mzg4NjE1MDA.*_ga_5EPM2P39FV*czE3NTQzMzMwNDgkbzEwMSRnMSR0MTc1NDMzNTI0MiRqNjAkbDAkaDE2NTE5NTM0NDM.*_fplc*cUxKN2FoY2gycnVMUkNlJTJCWkRyQ0tqR0klMkJuUnJXNm1mUmpvViUyRkMwaGRCY0Rvck44ZzJKWWZjS1cxY2FLNXZkJTJGeXlWclJ0bnFJcCUyQkxWakc4VklIcUNHYVhkM0lTQ0gwRUVrUFZwMUl1ekNRMlZVdFJsYTR5Y0NyeVFYSFNVdyUzRCUzRA..#search.2Fjobs",
                "external_id": "Search/Job Parameters",
            }
        ],
        "x_opencti_id": "1ec61033-8835-4452-8f5f-ccd8f0c1ab8c",
        "x_opencti_type": "Note",
        "type": "note",
        "created_by_ref": "identity--71f97ba4-389b-508f-9a4e-9a0c750c773d",
        "object_marking_refs": [
            "marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da"
        ],
        "abstract": "Last 24 hours",
    },
]
