from datetime import timedelta
from pydantic import Field, SecretStr
from connectors_sdk import (
    BaseConfigModel,
    BaseConnectorSettings,
    BaseExternalImportConnectorConfig,
    ListFromString,
)


class ExternalImportConnectorConfig(BaseExternalImportConnectorConfig):
    """
    Override the `BaseExternalImportConnectorConfig` to add parameters and/or defaults
    to the configuration for connectors of type `EXTERNAL_IMPORT`.
    """

    id: str = Field(
        description="A UUID v4 to identify the connector in OpenCTI.",
        default="7ad335a7-b218-4adf-a0c3-773cfa677290",
    )
    name: str = Field(
        description="The name of the connector.",
        default="CofenseThreathq",
    )
    scope: ListFromString = Field(
        description="The scope of the connector.",
        default=[],
    )
    duration_period: timedelta = Field(
        description="The period of time to await between two runs of the connector.",
        default=timedelta(hours=1),
    )


class CofenseThreathqConfig(BaseConfigModel):
    """
    Define parameters and/or defaults for the configuration specific to the `CofenseThreathqConnector`.
    """

    token_user: SecretStr = Field(
        description="Token user for Cofense ThreatHQ API authentication.",
    )
    token_password: SecretStr = Field(
        description="Token password for Cofense ThreatHQ API authentication.",
    )
    import_start_date: str = Field(
        default="P30D",
        description="Date from which data import should start (YYYY-MM-DD, full datetime, or ISO 8601 duration like P30D).",
    )
    api_base_url: str = Field(
        default="https://www.threathq.com/apiv1/",
        description="Cofense ThreatHQ API base URL.",
    )
    api_leaky_bucket_rate: int = Field(
        default=10,
        description="Leaky bucket rate per second for API rate limiting.",
    )
    api_leaky_bucket_capacity: int = Field(
        default=10,
        description="Leaky bucket capacity for API rate limiting.",
    )
    api_retry: int = Field(
        default=5,
        description="Maximum number of retry attempts in case of API failure.",
    )
    api_backoff: str = Field(
        default="PT30S",
        description="Exponential backoff duration between API retries (ISO 8601 format).",
    )
    impact_to_exclude: str = Field(
        default="",
        description="Comma-separated list of report impacts to exclude (e.g., None,Moderate,Major).",
    )
    import_report_pdf: bool = Field(
        default=True,
        description="Retrieve and attach PDF reports generated by Cofense ThreatHQ.",
    )
    tlp_level: str = Field(
        default="amber+strict",
        description="TLP marking for exported data (clear, green, amber, amber+strict, red).",
    )
    promote_observables_as_indicators: bool = Field(
        default=True,
        description="Create indicators based on observables from Cofense ThreatHQ.",
    )


class ConnectorSettings(BaseConnectorSettings):
    """
    Override `BaseConnectorSettings` to include `ExternalImportConnectorConfig` and `CofenseThreathqConfig`.
    """

    connector: ExternalImportConnectorConfig = Field(
        default_factory=ExternalImportConnectorConfig
    )
    cofense_threathq: CofenseThreathqConfig = Field(default_factory=CofenseThreathqConfig)
