from datetime import datetime, timedelta, timezone

from connectors_sdk import (
    BaseConfigModel,
    BaseConnectorSettings,
    BaseExternalImportConnectorConfig,
    DatetimeFromIsoString,
    ListFromString,
)
from connectors_sdk.models.enums import TLPLevel
from pydantic import Field, HttpUrl, SecretStr, field_validator


class ExternalImportConnectorConfig(BaseExternalImportConnectorConfig):
    """
    Override the `BaseExternalImportConnectorConfig` to add parameters and/or defaults
    to the configuration for connectors of type `EXTERNAL_IMPORT`.
    """

    id: str = Field(
        description="A UUID v4 to identify the connector in OpenCTI.",
        default="7ad335a7-b218-4adf-a0c3-773cfa677290",
    )
    name: str = Field(
        description="The name of the connector.",
        default="CofenseThreathq",
    )
    scope: ListFromString = Field(
        description="The scope of the connector.",
        default=[],
    )
    duration_period: timedelta = Field(
        description="The period of time to await between two runs of the connector.",
        default=timedelta(hours=1),
    )


class CofenseThreathqConfig(BaseConfigModel):
    """
    Define parameters and/or defaults for the configuration specific to the `CofenseThreathqConnector`.
    """

    token_user: SecretStr = Field(
        description="Token user for Cofense ThreatHQ API authentication.",
    )
    token_password: SecretStr = Field(
        description="Token password for Cofense ThreatHQ API authentication.",
    )
    import_start_date: DatetimeFromIsoString = Field(
        # `default_factory` is used to set a dynamic default value (datetime) at runtime
        default_factory=lambda: datetime.now(timezone.utc) - timedelta(days=30),
        description="Date from which data import should start (ISO 8601 datetime or duration, e.g. '2023-10-01' or 'P30D'). Default: 30 days ago.",
    )
    api_base_url: HttpUrl = Field(
        default=HttpUrl("https://www.threathq.com/apiv1/"),
        description="Cofense ThreatHQ API base URL.",
    )
    api_leaky_bucket_rate: int = Field(
        default=10,
        description="Leaky bucket rate per second for API rate limiting.",
    )
    api_leaky_bucket_capacity: int = Field(
        default=10,
        description="Leaky bucket capacity for API rate limiting.",
    )
    api_retry: int = Field(
        default=5,
        description="Maximum number of retry attempts in case of API failure.",
    )
    api_backoff: timedelta = Field(
        default=timedelta(seconds=30),
        description="Exponential backoff duration between API retries (ISO 8601 duration format).",
    )
    impact_to_exclude: ListFromString = Field(
        default=[],
        description="Comma-separated list of report impacts to exclude (e.g., None,Moderate,Major).",
    )
    import_report_pdf: bool = Field(
        default=True,
        description="Retrieve and attach PDF reports generated by Cofense ThreatHQ.",
    )
    tlp_level: TLPLevel = Field(
        default=TLPLevel.AMBER_STRICT,
        description="TLP marking for exported data (clear, white, green, amber, amber+strict, red).",
    )
    promote_observables_as_indicators: bool = Field(
        default=True,
        description="Create indicators based on observables from Cofense ThreatHQ.",
    )

    @field_validator("impact_to_exclude", mode="after")
    @classmethod
    def _lowercase_impact_to_exclude(cls, value: list[str]) -> list[str]:
        return [item.strip().lower() for item in value if item.strip()]

    @field_validator("tlp_level", mode="before")
    @classmethod
    def _lowercase_tlp_level(cls, value: str) -> str:
        return value.lower() if isinstance(value, str) else value


class ConnectorSettings(BaseConnectorSettings):
    """
    Override `BaseConnectorSettings` to include `ExternalImportConnectorConfig` and `CofenseThreathqConfig`.
    """

    connector: ExternalImportConnectorConfig = Field(
        default_factory=ExternalImportConnectorConfig
    )
    cofense_threathq: CofenseThreathqConfig = Field(
        default_factory=CofenseThreathqConfig
    )
