"""Converts a GTI report to a STIX report object."""

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, List, Optional, Tuple

from connector.src.custom.models.gti_reports.gti_report_model import (
    GTIReportData,
    ReportModel,
    Technology,
)
from connector.src.stix.octi.models.report_model import OctiReportModel
from connector.src.stix.v21.models.cdts.external_reference_model import (
    ExternalReferenceModel,
)
from connector.src.stix.v21.models.ovs.report_type_ov_enums import ReportTypeOV
from connector.src.utils.converters.generic_converter_config import BaseMapper
from connector.src.utils.markdown_to_html import markdown_to_html
from stix2.v21 import Identity, MarkingDefinition, Report, Software  # type: ignore

logger = logging.getLogger(__name__)


class GTIReportToSTIXReport(BaseMapper):
    """Converts a GTI report to a STIX report object."""

    def __init__(
        self,
        report: GTIReportData,
        organization: Identity,
        tlp_marking: MarkingDefinition,
        **kwargs: Any,
    ) -> None:
        """Initialize the GTIReportToSTIXReport object.

        Args:
            report (GTIReportData): The GTI report data to convert.
            organization (Identity): The organization identity object.
            tlp_marking (MarkingDefinition): The TLP marking definition.

        """
        self.report = report
        self.organization = organization
        self.tlp_marking = tlp_marking

    def to_stix(self) -> Report:
        """Convert the GTI report to a STIX report object.

        Returns:
            Report: The STIX report object.

        """
        if not hasattr(self.report, "attributes") or not self.report.attributes:
            raise ValueError("Invalid GTI report data")

        attributes = self.report.attributes

        name = attributes.name
        if len(name) < 2:
            raise ValueError("Report name must be at least 2 characters long")

        created, modified = self._get_timestamps(attributes)
        labels = self._extract_labels(attributes)
        external_references = self._build_external_references(attributes)
        report_type = self._determine_report_type(attributes)
        confidence = self._map_confidence(attributes.report_confidence)

        author_id = (
            self.author_identity.id
            if hasattr(self, "author_identity") and self.author_identity
            else self.organization.id
        )

        # Build enhanced content with executive summary and analyst insights
        enhanced_content = self._build_enhanced_content(attributes)

        # Build create kwargs, only include confidence if mapped
        create_kwargs: dict = {}
        if confidence is not None:
            create_kwargs["confidence"] = confidence

        report = OctiReportModel.create(
            name=name,
            created=created,
            modified=modified,
            description=attributes.autogenerated_summary,
            report_types=[report_type],
            published=created,
            object_refs=[],
            organization_id=author_id,
            marking_ids=[self.tlp_marking.id],
            labels=labels,
            external_references=[
                ref.model_dump(exclude_none=True) for ref in external_references
            ],
            content=enhanced_content,
            **create_kwargs,
        )

        return report

    def add_author_identity(self, author_identity: Identity) -> None:
        """Add or update the author identity for the report.

        Args:
            author_identity: The author identity to set

        """
        self.author_identity = author_identity

    @staticmethod
    def _get_timestamps(attributes: ReportModel) -> Tuple[datetime, datetime]:
        """Extract creation and modification timestamps from attributes.

        If a resolved date is in the future, the day and month are swapped.
        This works around a known issue where dates such as 2026-02-12
        (February 12) are interpreted downstream as 2026-12-02 (December 2).

        Args:
            attributes: The report attributes

        Returns:
            tuple: (created, modified) datetime objects

        """
        created = datetime.fromtimestamp(attributes.creation_date, tz=timezone.utc)
        modified = datetime.fromtimestamp(
            attributes.last_modification_date, tz=timezone.utc
        )

        now_utc = datetime.now(tz=timezone.utc)

        created = GTIReportToSTIXReport._fix_swapped_date(
            created, now_utc, "creation_date", attributes.name
        )
        modified = GTIReportToSTIXReport._fix_swapped_date(
            modified, now_utc, "last_modification_date", attributes.name
        )

        logger.debug(
            "[GTIReportMapper] Report '%s' timestamps: "
            "creation_date=%s -> %s, last_modification_date=%s -> %s",
            attributes.name,
            attributes.creation_date,
            created.isoformat(),
            attributes.last_modification_date,
            modified.isoformat(),
        )

        return created, modified

    @staticmethod
    def _fix_swapped_date(
        dt: datetime,
        now_utc: datetime,
        field_name: str,
        report_name: str,
    ) -> datetime:
        """Swap day and month if *dt* is in the future and swapping fixes it.

        Some dates are misinterpreted downstream (e.g. 2026-02-12 rendered as
        December 2).  When we detect the resolved timestamp is in the future
        and the day value is a valid month (1-12), we swap month <--> day so
        that the date is no longer in the future.

        Args:
            dt: The datetime to check.
            now_utc: The current UTC time.
            field_name: Name of the field (for logging).
            report_name: Report name (for logging).

        Returns:
            The original datetime, or the corrected one with day/month swapped.

        """
        if dt <= now_utc:
            return dt

        # Only attempt the swap when the day value is a valid month (1-12)
        if dt.day > 12:
            logger.warning(
                "[GTIReportMapper] Report '%s' %s is in the future (%s) "
                "but day=%d cannot be a valid month; leaving unchanged.",
                report_name,
                field_name,
                dt.isoformat(),
                dt.day,
            )
            return dt

        try:
            swapped = dt.replace(month=dt.day, day=dt.month)
        except ValueError:
            # e.g. swapping would produce Feb 30 — leave unchanged
            logger.warning(
                "[GTIReportMapper] Report '%s' %s is in the future (%s) "
                "but swapping day/month produces an invalid date; leaving unchanged.",
                report_name,
                field_name,
                dt.isoformat(),
            )
            return dt

        if swapped <= now_utc:
            logger.warning(
                "[GTIReportMapper] Report '%s' %s was in the future (%s). "
                "Swapped day/month to correct it -> %s.",
                report_name,
                field_name,
                dt.isoformat(),
                swapped.isoformat(),
            )
            return swapped

        # Swap didn't help — return original
        logger.warning(
            "[GTIReportMapper] Report '%s' %s is in the future (%s) "
            "and swapping day/month (%s) didn't resolve it; leaving unchanged.",
            report_name,
            field_name,
            dt.isoformat(),
            swapped.isoformat(),
        )
        return dt

    @staticmethod
    def _extract_labels(attributes: ReportModel) -> List[str]:
        """Extract labels from report attributes.

        Args:
            attributes: The report attributes

        Returns:
            list: Extracted labels

        """
        labels = []
        if attributes.intended_effects:
            labels.extend(attributes.intended_effects)
        if attributes.threat_scape:
            labels.extend(attributes.threat_scape)
        if attributes.motivations:
            for motivation in attributes.motivations:
                if motivation.value:
                    labels.append(motivation.value)
        if attributes.threat_categories:
            for category in attributes.threat_categories:
                if category and category not in labels:
                    labels.append(category)
        if attributes.affected_systems:
            for system in attributes.affected_systems:
                if system and system not in labels:
                    labels.append(system)
        if attributes.targeted_informations:
            for info in attributes.targeted_informations:
                if info and info not in labels:
                    labels.append(info)
        return labels

    @staticmethod
    def _map_confidence(report_confidence: Optional[str]) -> Optional[int]:
        """Map GTI report confidence string to STIX confidence integer (0-100).

        Args:
            report_confidence: GTI confidence string

        Returns:
            Optional[int]: STIX confidence value (0-100) or None if unmapped

        """
        if not report_confidence:
            return None

        confidence_map = {
            "high": 85,
            "moderate": 50,
            "medium": 50,
            "low": 15,
            "confirmed": 100,
            "assessed": 75,
            "possible": 25,
        }

        return confidence_map.get(report_confidence.strip().lower())

    def _build_external_references(
        self, attributes: ReportModel
    ) -> List[ExternalReferenceModel]:
        """Build external references from report attributes.

        Args:
            attributes: The report attributes

        Returns:
            list: External references

        """
        external_references = []
        if attributes.link:
            external_reference = ExternalReferenceModel(
                source_name="Source link",
                description="Source link for the Report",
                url=attributes.link,
            )
            external_references.append(external_reference)

        if self.report.id:
            external_reference = ExternalReferenceModel(
                source_name="Google Threat Intelligence Platform",
                description="Google Threat Intelligence Report Link",
                url=f"https://www.virustotal.com/gui/collection/{self.report.id}",
            )
            external_references.append(external_reference)
        return external_references

    @staticmethod
    def _determine_report_type(attributes: ReportModel) -> ReportTypeOV:
        """Determine the report type based on attributes.

        Args:
            attributes: The report attributes

        Returns:
            ReportTypeOV: The determined report type

        """
        if attributes.report_type is None:
            return ReportTypeOV("unknown")
        return ReportTypeOV(attributes.report_type)

    @staticmethod
    def add_object_refs(objects_to_add: List[str], existing_report: Any) -> Any:
        """Add object references to an existing report while preserving all report data.

        Handles both mutable Pydantic ReportModel objects and immutable STIX2 Report objects.
        For STIX2 objects, this creates a new object with updated refs.
        For Pydantic models, this modifies the object in place.

        Args:
            objects_to_add: Object ID(s) to add to the report's object_refs.
            existing_report: The existing report object to update (Pydantic or STIX2).

        Returns:
            The updated report with all original data preserved.

        """
        from stix2.v21 import Report as STIX2Report
        from stix2.base import _STIXBase
        
        # Get current refs
        if hasattr(existing_report, "object_refs"):
            current_refs = existing_report.object_refs
            updated_refs = list(current_refs) if current_refs else []
        elif hasattr(existing_report, "get"):
            updated_refs = list(existing_report.get("object_refs", []) or [])
        else:
            updated_refs = []

        # Add new refs (avoiding duplicates)
        for obj_id in objects_to_add:
            if obj_id not in updated_refs:
                updated_refs.append(obj_id)

        # Check if this is an immutable STIX2 object
        is_stix2_object = isinstance(existing_report, _STIXBase)
        
        if is_stix2_object:
            # STIX2 objects are immutable - we need to create a new version
            # Use new_version() if available, otherwise recreate
            try:
                return existing_report.new_version(object_refs=updated_refs)
            except Exception:
                # Fallback: serialize and recreate
                report_dict = dict(existing_report)
                report_dict["object_refs"] = updated_refs
                return STIX2Report(**report_dict)
        else:
            # Pydantic model - can be modified directly
            existing_report.object_refs = updated_refs
            return existing_report

    @staticmethod
    def _build_enhanced_content(attributes: ReportModel) -> str:
        """Build enhanced content with executive summary and analyst insights.

        Prepends executive summary and analyst comment to the main content
        with HTML formatting. Any markdown in the content fields is converted
        to proper HTML for clean rendering in OpenCTI.

        Args:
            attributes: The report attributes

        Returns:
            str: Enhanced content as clean HTML

        """
        content_parts = []

        # Add executive summary if available
        if attributes.executive_summary:
            summary_html = markdown_to_html(attributes.executive_summary)
            content_parts.append(
                f"<h1>Executive Summary</h1>\n{summary_html}"
            )

        # Add analyst comment if available
        if attributes.analyst_comment:
            comment_html = markdown_to_html(attributes.analyst_comment)
            content_parts.append(
                f"<h1>Analyst Insights</h1>\n{comment_html}"
            )

        # Add main content (may be HTML, markdown, or mixed)
        if attributes.content:
            main_content_html = markdown_to_html(attributes.content)
            if content_parts:
                content_parts.append(f"<h1>Report Content</h1>\n{main_content_html}")
            else:
                content_parts.append(main_content_html)

        return "\n\n".join(content_parts) if content_parts else ""
