version: '3'
services:
  google-secops-siem:
    image: opencti/connector-google-secops-siem:latest
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # Connector's definition parameters
      # - CONNECTOR_ID=9257254e-b4ef-4592-ab11-6d37d4aa321f
      # - CONNECTOR_NAME=Google SecOps SIEM
      # - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_LIVE_STREAM_ID=ChangeMe # ID of the live stream created in the OpenCTI UI
      # - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true
      # - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true

      # Connector's custom execution parameters
      # - SECOPS_SIEM_PROJECT_REGION=us
      - SECOPS_SIEM_PROJECT_ID=ChangeMe
      - SECOPS_SIEM_PROJECT_INSTANCE=ChangeMe
      - SECOPS_SIEM_PRIVATE_KEY_ID=ChangeMe
      - SECOPS_SIEM_PRIVATE_KEY=ChangeMe
      - SECOPS_SIEM_CLIENT_EMAIL=ChangeMe
      - SECOPS_SIEM_CLIENT_ID=ChangeMe
      # - SECOPS_SIEM_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      # - SECOPS_SIEM_TOKEN_URI=https://oauth2.googleapis.com/token
      # - SECOPS_SIEM_AUTH_PROVIDER_CERT=https://www.googleapis.com/oauth2/v1/certs
      - SECOPS_SIEM_CLIENT_CERT_URL=ChangeMe
    restart: always
