# syntax=docker/dockerfile:1

FROM filigran/python-fips:latest

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk add --no-cache libmagic && pip install --no-cache-dir pycti==6.7.8

# Install dependencies
# Avoid an image layer for those files.
RUN --mount=type=bind,source=src/requirements.txt,target=requirements.txt \
    python -m pip install --no-cache-dir -r requirements.txt

# Copy the connector
COPY --chmod=777 src .
ENV HOME=/opt/opencti-connector-import-document

# Execute the connector
CMD [ "python", "main.py" ]

ENV CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
