version: '3'
services:
  connector-google-dtm:
    image: opencti/connector-google-dtm:6.9.10
    environment:
      # OpenCTI connection parameters
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # Connector's common parameters
      - CONNECTOR_ID=ChangeMe
      - "CONNECTOR_NAME=Google DTM"
      - CONNECTOR_SCOPE=google-dtm
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_DURATION_PERIOD=PT1H
       # Connector's custom execution parameters
      - GOOGLE_DTM_API_KEY=ChangeMe
      - GOOGLE_DTM_TLP=amber+strict
      - GOOGLE_DTM_IMPORT_START_DATE=P10D
      - GOOGLE_DTM_ALERT_SEVERITY=
      - GOOGLE_DTM_ALERT_TYPE=
    restart: always