"""The module defines the IndustrySectorOV enumeration for various industry sectors."""

from connector.src.stix.v21.models.ovs.base_open_vocab import BaseOV


class IndustrySectorOV(BaseOV):
    """Industry Sector Enumeration."""

    AGRICULTURE = "agriculture"
    AEROSPACE = "aerospace"
    AUTOMOTIVE = "automotive"
    COMMUNICATIONS = "communications"
    CONSTRUCTION = "construction"
    DEFENCE = "defence"
    EDUCATION = "education"
    ENERGY = "energy"
    ENTERTAINMENT = "entertainment"
    FINANCIAL_SERVICES = "financial-services"
    GOVERNMENT_NATIONAL = "government-national"
    GOVERNMENT_REGIONAL = "government-regional"
    GOVERNMENT_LOCAL = "government-local"
    GOVERNMENT_PUBLIC_SERVICES = "government-public-services"
    HEALTHCARE = "healthcare"
    HOSPITALITY_LEISURE = "hospitality-leisure"
    INFRASTRUCTURE = "infrastructure"
    INSURANCE = "insurance"
    MANUFACTURING = "manufacturing"
    MINING = "mining"
    NON_PROFIT = "non-profit"
    PHARMACEUTICALS = "pharmaceuticals"
    RETAIL = "retail"
    TECHNOLOGY = "technology"
    TELECOMMUNICATIONS = "telecommunications"
    TRANSPORTATION = "transportation"
    UTILITIES = "utilities"
