version: '3'
services:
  connector-hybrid-analysis-sandbox:
    image: opencti/connector-hybrid-analysis-sandbox:latest
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # - CONNECTOR_ID=22538379-7caa-41ac-a401-c752db2cd2ac
      # - "CONNECTOR_NAME=Hybrid Analysis (Sandbox Windows 10 64bit)"
      # - "CONNECTOR_SCOPE=StixFile,Artifact,Url,Domain-Name,Hostname"
      # - CONNECTOR_AUTO=true
      # - CONNECTOR_LOG_LEVEL=error
      - HYBRID_ANALYSIS_SANDBOX_TOKEN=ChangeMe
      # - HYBRID_ANALYSIS_SANDBOX_ENVIRONMENT_ID=110
      # - HYBRID_ANALYSIS_SANDBOX_MAX_TLP=TLP:AMBER
    restart: always
