version: '3'
services:
  connector-microsoft-defender-incidents:
    image: opencti/connector-microsoft-defender-incidents:latest
    environment:
      # Connector's generic execution parameters
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe

      # Connector's definition parameters REQUIRED
      - CONNECTOR_ID=ChangeMe
      # - "CONNECTOR_NAME=Microsoft Defender Incidents"
      # - CONNECTOR_SCOPE=defender
      # - CONNECTOR_LOG_LEVEL=error
      # - CONNECTOR_DURATION_PERIOD=PT1H

      # Connector's definition parameters OPTIONAL
      # - CONNECTOR_QUEUE_THRESHOLD=500 # Default 500Mo, Float accepted
      # - CONNECTOR_RUN_AND_TERMINATE=false # Default false, true run connector once
      # - CONNECTOR_SEND_TO_QUEUE=true # Default true
      # - CONNECTOR_SEND_TO_DIRECTORY=false # Default false
      # - CONNECTOR_SEND_TO_DIRECTORY_PATH=ChangeMe # if CONNECTOR_SEND_TO_DIRECTORY is true, you must specify a path
      # - CONNECTOR_SEND_TO_DIRECTORY_RETENTION=7 # Default 7, in days

      # Connector's custom execution parameters
      - MICROSOFT_DEFENDER_INCIDENTS_TENANT_ID=ChangeMe
      - MICROSOFT_DEFENDER_INCIDENTS_CLIENT_ID=ChangeMe
      - MICROSOFT_DEFENDER_INCIDENTS_CLIENT_SECRET=ChangeMe
      # - MICROSOFT_DEFENDER_INCIDENTS_IMPORT_START_DATE=
      # - MICROSOFT_DEFENDER_INCIDENTS_API_BASE_URL=https://graph.microsoft.com/v1.0
      # - MICROSOFT_DEFENDER_INCIDENTS_INCIDENT_PATH=/security/incidents
    restart: always
