version: '3'
services:
  connector-bitsight-incidents:
    image: opencti/connector-bitsight-incidents:latest
    environment:
      # Generic parameters (connection with OpenCTI)
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      # Common parameters for connectors of type EXTERNAL_IMPORT
      - CONNECTOR_ID=CHANGEME
      - "CONNECTOR_NAME=BitSight Incidents"
      - CONNECTOR_SCOPE=CHANGEME
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_DURATION_PERIOD=PT1H
      # Custom parameters for connector-bitsight
      - BITSIGHT_CLIENT_ID=CHANGEME
      - BITSIGHT_CLIENT_SECRET=CHANGEME
      - BITSIGHT_TLP_LEVEL=clear
    restart: always

