version: '3'
services:
  connector-crowdstrike-incidents:
    image: opencti/connector-crowdstrike-incidents:latest
    environment:
      # OpenCTI configuration
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      # Common connector configuration
      #- CONNECTOR_ID=53e6bf2e-48bb-4ce0-8d2d-537b3343576b
      #- CONNECTOR_NAME=CrowdStrike Incidents
      #- CONNECTOR_SCOPE=crowdstrike-incidents
      #- CONNECTOR_LOG_LEVEL=error
      #- CONNECTOR_DURATION_PERIOD=PT5M
      # Connector configuration
      #- CROWDSTRIKE_INCIDENTS_API_BASE_URL=https://api.crowdstrike.com
      - CROWDSTRIKE_INCIDENTS_CLIENT_ID=ChangeMe
      - CROWDSTRIKE_INCIDENTS_CLIENT_SECRET=ChangeMe
      #- CROWDSTRIKE_INCIDENTS_IMPORT_START_DATE=P7D
      #- CROWDSTRIKE_INCIDENTS_PRODUCTS=ngsiem
      #- CROWDSTRIKE_INCIDENTS_SEVERITY_MIN=low
      #- CROWDSTRIKE_INCIDENTS_INCLUDE_HIDDEN=false
      #- CROWDSTRIKE_INCIDENTS_TLP_LEVEL=amber+strict
    restart: always
