version: '3'
services:
  connector-ransomwarelive:
    image: opencti/connector-ransomwarelive:latest
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_NAME=RansomwareLive
      - CONNECTOR_SCOPE=ransomwarelive
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_PULL_HISTORY=false
      - CONNECTOR_HISTORY_START_YEAR=2023
      - CONNECTOR_CREATE_THREAT_ACTOR=false
      - CONNECTOR_CREATE_LEAK_SITE_DOMAINS=true
      - CONNECTOR_CREATE_LEAK_POST_REFS=true
    restart: always
