version: '3'
services:
  connector-paloalto-wildfire:
    image: opencti/connector-paloalto-wildfire:latest # 'paloalto-wildfire' being the name of connector's directory
    environment:
      # Generic parameters (connection with OpenCTI)
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=CHANGEME
      # Common parameters for connectors of type INTERNAL_ENRICHMENT
      - CONNECTOR_ID=CHANGEME
      - CONNECTOR_NAME=Palo Alto Networks WildFire # optional (default: 'Palo Alto Networks WildFire')
      - CONNECTOR_SCOPE=StixFile,Artifact # optional (default: 'StixFile,Artifact')
      - CONNECTOR_LOG_LEVEL=error # optional (default: 'error')
      - CONNECTOR_AUTO=false # optional (default: false)
      # Custom parameters for connector-paloalto-wildfire
      - PALOALTO_WILDFIRE_API_KEY=CHANGEME
      - PALOALTO_WILDFIRE_API_BASE_URL=https://wildfire.paloaltonetworks.com/publicapi # optional (default: cloud endpoint)
      - PALOALTO_WILDFIRE_MAX_TLP=TLP:AMBER # optional, available values: 'TLP:CLEAR', 'TLP:WHITE', 'TLP:GREEN', 'TLP:AMBER', 'TLP:AMBER+STRICT', 'TLP:RED' (default: 'TLP:AMBER')
    restart: always
