version: '3'
services:
  connector-cisa-ics-advisories:
    image: opencti/connector-cisa-ics-advisories:latest
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
    restart: always
