version: '3'

services:
  connector-ddosia:
    image: opencti/connector-ddosia:latest
    container_name: connector-ddosia
    restart: always
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=YOUR_OPENCTI_TOKEN
      - CONNECTOR_ID=YOUR_CONNECTOR_ID
      - CONNECTOR_NAME=DDoSIA Connector
      - CONNECTOR_SCOPE=ddosia
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_DURATION_PERIOD=1h
      - DDOSIA_API_BASE_URL=http://api.witha.name
      - DDOSIA_TLP_LEVEL=green
      - DDOSIA_IMPORT_START_TIMESTAMP=null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - opencti

networks:
  opencti:
    external: true
