"""Tests for the alert content generated by `ConverterToStix`.

DTM omits optional fields instead of returning them null, so these tests pin
that an incomplete document still produces its `alert.md` attachment and, for
`create_channel`, that it does not abort the whole run.
"""

import base64
from unittest.mock import MagicMock

import pytest
from src.google_dtm_connector.converter_to_stix import ConverterToStix

_ACCOUNT_DISCOVERY_ALERT = {
    "id": "da1pueokorjs73af1j90",
    "title": "Credential leak on acme.com",
    "created_at": "2026-08-22T01:00:00.000Z",
    "updated_at": "2026-08-22T01:30:00.000Z",
    "severity": "high",
    "alert_type": "Compromised Credentials",
    "doc": {
        "__type": "account_discovery",
        "source_url": "https://forum.invalid/thread/1",
        "source_file": {
            "filename": "combo.txt",
            "hashes": {"md5": "d41d8cd98f00b204e9800998ecf8427e"},
        },
        "service_account": {
            "login": "jdoe@acme.com",
            "email_domain": "acme.com",
            "service": {"inet_location": {"domain": "acme.com"}},
        },
    },
}

_MESSAGE_ALERT = {
    "id": "da1pueokorjs73af1j91",
    "title": "Mention on a Telegram channel",
    "created_at": "2026-08-22T01:00:00.000Z",
    "updated_at": "2026-08-22T01:30:00.000Z",
    "severity": "medium",
    "alert_type": "Forum",
    "doc": {
        "__type": "message",
        "body": "acme.com is up for sale",
        # No channel_info, no messenger, no sender.
        "channel": {"name": "leaks", "channel_url": "https://t.me/leaks"},
    },
}


@pytest.fixture
def converter() -> ConverterToStix:
    return ConverterToStix(MagicMock(), tlp="clear")


def _attachments(stix_objects):
    incident = next(obj for obj in stix_objects if obj["type"] == "incident")
    return incident.get("x_opencti_files", [])


def _alert_markdown(stix_objects):
    (attachment,) = _attachments(stix_objects)
    assert attachment["name"] == "alert.md"
    return base64.b64decode(attachment["data"]).decode("utf-8")


# --------------------------------------------------------------------------
# A missing optional field no longer costs the attachment
# --------------------------------------------------------------------------


def test_account_discovery_without_a_plaintext_password(converter):
    """The reported bug: service_account.password is absent, .get() raised."""
    stix_objects = converter.create_incident(_ACCOUNT_DISCOVERY_ALERT)

    markdown = _alert_markdown(stix_objects)
    converter.helper.connector_logger.error.assert_not_called()
    # The absent value is rendered empty, the ones that are there are kept.
    assert "- **Password**: None\n" in markdown
    assert "- **Login**: jdoe@acme.com\n" in markdown
    assert "- **MD5**: d41d8cd98f00b204e9800998ecf8427e\n" in markdown
    assert "- **SHA256**: None\n" in markdown


def test_message_alert_without_channel_info(converter):
    stix_objects = converter.create_incident(_MESSAGE_ALERT)

    markdown = _alert_markdown(stix_objects)
    converter.helper.connector_logger.error.assert_not_called()
    assert "- **Channel**: leaks\n" in markdown
    assert "- **Channel Description**: None\n" in markdown
    assert "- **Author**: None\n" in markdown


@pytest.mark.parametrize(
    "doc",
    [
        {"__type": "account_discovery"},
        {"__type": "message"},
        {"__type": "paste"},
        {"__type": "document_analysis"},
        {"__type": "shop_listing"},
        {"__type": "domain_discovery"},
        {"__type": "web_content_publish"},
        {"__type": "something_new"},
    ],
)
def test_an_empty_document_still_produces_an_attachment(converter, doc):
    """Every alert type must survive a document reduced to its type."""
    stix_objects = converter.create_incident({**_ACCOUNT_DISCOVERY_ALERT, "doc": doc})

    assert len(_attachments(stix_objects)) == 1
    converter.helper.connector_logger.error.assert_not_called()


# --------------------------------------------------------------------------
# create_channel sits outside create_incident's try/except
# --------------------------------------------------------------------------


def test_a_channel_without_channel_info_does_not_abort_the_run(converter):
    """`create_channel` is called outside the try: it used to kill the run."""
    stix_objects = converter.create_incident(_MESSAGE_ALERT)

    channel = next(obj for obj in stix_objects if obj["type"] == "channel")
    assert channel["name"] == "[] - leaks"
    assert channel["external_references"][0]["url"] == "https://t.me/leaks"


def test_a_channel_reduced_to_nothing_does_not_raise(converter):
    channel = converter.create_channel({})

    assert channel["type"] == "channel"
    # stix2 drops the empty list rather than storing it.
    assert "external_references" not in channel
